/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  MockMineContract,
  MockMineContractInterface,
} from "../../../../src/mocks/DQMiningTestMocks.sol/MockMineContract";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "distributeDRankReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "distributeLPReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "distributeNodeReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080604052348015600e575f5ffd5b50609a80601a5f395ff3fe6080604052348015600e575f5ffd5b5060043610603a575f3560e01c8063450b545714603e57806346bb0cd614603e5780637c85bb6214603e575b5f5ffd5b604c6049366004604e565b50565b005b5f60208284031215605d575f5ffd5b503591905056fea2646970667358221220073cddd97f4348c2d9f515d3e777b3cc474ccc5d753cffc45ca422b76254ec6164736f6c63430008230033";

type MockMineContractConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockMineContractConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockMineContract__factory extends ContractFactory {
  constructor(...args: MockMineContractConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockMineContract & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockMineContract__factory {
    return super.connect(runner) as MockMineContract__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockMineContractInterface {
    return new Interface(_abi) as MockMineContractInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockMineContract {
    return new Contract(address, _abi, runner) as unknown as MockMineContract;
  }
}
