/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDQCardAdmin,
  IDQCardAdminInterface,
} from "../../../src/DQMAdmin.sol/IDQCardAdmin";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "setAdminContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "setCoreContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_addr",
        type: "address",
      },
    ],
    name: "setStakeContract",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IDQCardAdmin__factory {
  static readonly abi = _abi;
  static createInterface(): IDQCardAdminInterface {
    return new Interface(_abi) as IDQCardAdminInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IDQCardAdmin {
    return new Contract(address, _abi, runner) as unknown as IDQCardAdmin;
  }
}
