/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DQProjectInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BEP20_TOKEN"
      | "BLACKHOLE"
      | "BURN_DECREMENT"
      | "INVEST_MAX_FINAL"
      | "INVEST_MAX_START"
      | "INVEST_MAX_STEP"
      | "INVEST_MIN"
      | "MIN_BURN_RATE"
      | "PHASE_DURATION"
      | "addPartner"
      | "addPartnerBatch"
      | "adminWithdrawBEP20"
      | "adminWithdrawBNB"
      | "adminWithdrawDQ"
      | "allUsers"
      | "blockMining"
      | "burnRate"
      | "buyNode"
      | "canDeposit"
      | "checkNodeQualified"
      | "claimDTeam"
      | "claimLp"
      | "claimNft"
      | "claimPartner"
      | "dAccPerShare"
      | "dRewardDebt"
      | "dThresholds"
      | "dTotalUsers"
      | "dailyReleaseRate"
      | "deposit"
      | "dqCard"
      | "dqPrice"
      | "dqToken"
      | "dynamicPool"
      | "feePool"
      | "foundationWallet"
      | "getBEP20Balance"
      | "getContractBalance"
      | "getCurrentMaxInvest"
      | "getNodeInfo"
      | "getPartnerCount"
      | "getPrice"
      | "getRestrictedCount"
      | "getSingleStake"
      | "getUser"
      | "insurancePool"
      | "isPartnerWhite"
      | "lastBlockTime"
      | "lastBlockTimeV2"
      | "levelRates"
      | "lpAccPerShare"
      | "lpPool"
      | "nftAccPerShare"
      | "nftRewardDebtAcc"
      | "operationPool"
      | "owner"
      | "partnerAccPerShare"
      | "partnerDebt"
      | "partnerDqAccPerShare"
      | "partnerWhiteList"
      | "register"
      | "removePartner"
      | "renounceOwnership"
      | "restrictAddress"
      | "restrictAddressBatch"
      | "restrictedAddresses"
      | "restrictedDebt"
      | "setFoundationWallet"
      | "setPrice"
      | "singleStakes"
      | "stakeDQ"
      | "stakeFeeAccPerShare"
      | "stakePeriods"
      | "stakeRates"
      | "startTime"
      | "swapBEP20ForDQ"
      | "swapDQForBEP20"
      | "totalLPShares"
      | "totalRestrictedCount"
      | "totalSingleStaked"
      | "transferOwnership"
      | "unrestrictAddress"
      | "unstakeDQ"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddPartner"
      | "BlockMining"
      | "BuyNode"
      | "ClaimDTeam"
      | "ClaimLp"
      | "ClaimNft"
      | "ClaimPartner"
      | "DLevelUp"
      | "Deposit"
      | "LevelUp"
      | "LineQualified"
      | "OwnershipTransferred"
      | "PriceUpdated"
      | "Register"
      | "RemovePartner"
      | "RestrictAddress"
      | "StakeDQ"
      | "SwapBEP20ForDQ"
      | "SwapDQForBEP20"
      | "UnrestrictAddress"
      | "UnstakeDQ"
      | "Withdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BEP20_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BLACKHOLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "BURN_DECREMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVEST_MAX_FINAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVEST_MAX_START",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVEST_MAX_STEP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVEST_MIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_BURN_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PHASE_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addPartner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addPartnerBatch",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdrawBEP20",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdrawBNB",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdrawDQ",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "allUsers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "blockMining",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "burnRate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buyNode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canDeposit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkNodeQualified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDTeam",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claimLp", values?: undefined): string;
  encodeFunctionData(functionFragment: "claimNft", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimPartner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dAccPerShare",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dRewardDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dThresholds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dTotalUsers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyReleaseRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "dqCard", values?: undefined): string;
  encodeFunctionData(functionFragment: "dqPrice", values?: undefined): string;
  encodeFunctionData(functionFragment: "dqToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "dynamicPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "foundationWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBEP20Balance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentMaxInvest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNodeInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPartnerCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getRestrictedCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSingleStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "insurancePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isPartnerWhite",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastBlockTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lastBlockTimeV2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "levelRates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lpAccPerShare",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lpPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nftAccPerShare",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nftRewardDebtAcc",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "operationPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "partnerAccPerShare",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "partnerDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "partnerDqAccPerShare",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "partnerWhiteList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removePartner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "restrictAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "restrictAddressBatch",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "restrictedAddresses",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "restrictedDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFoundationWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "singleStakes",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeDQ",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeFeeAccPerShare",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakePeriods",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeRates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "startTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapBEP20ForDQ",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapDQForBEP20",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "totalLPShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRestrictedCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSingleStaked",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unrestrictAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeDQ",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BEP20_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BLACKHOLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BURN_DECREMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVEST_MAX_FINAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVEST_MAX_START",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVEST_MAX_STEP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "INVEST_MIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_BURN_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PHASE_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addPartner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addPartnerBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdrawBEP20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdrawBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdrawDQ",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blockMining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burnRate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyNode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkNodeQualified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimDTeam", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimLp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimPartner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dAccPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dRewardDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dTotalUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyReleaseRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dqCard", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dqPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dqToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dynamicPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "foundationWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBEP20Balance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentMaxInvest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNodeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPartnerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRestrictedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSingleStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "insurancePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPartnerWhite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastBlockTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastBlockTimeV2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "levelRates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lpAccPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nftAccPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftRewardDebtAcc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "operationPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "partnerAccPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "partnerDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "partnerDqAccPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "partnerWhiteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removePartner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restrictAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restrictAddressBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restrictedAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restrictedDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFoundationWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "singleStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakeDQ", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeFeeAccPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakePeriods",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakeRates", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapBEP20ForDQ",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapDQForBEP20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLPShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalRestrictedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSingleStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unrestrictAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstakeDQ", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace AddPartnerEvent {
  export type InputTuple = [partner: AddressLike];
  export type OutputTuple = [partner: string];
  export interface OutputObject {
    partner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BlockMiningEvent {
  export type InputTuple = [
    release: BigNumberish,
    burn: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [release: bigint, burn: bigint, timestamp: bigint];
  export interface OutputObject {
    release: bigint;
    burn: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BuyNodeEvent {
  export type InputTuple = [
    user: AddressLike,
    cardType: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, cardType: bigint, amount: bigint];
  export interface OutputObject {
    user: string;
    cardType: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimDTeamEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimLpEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimNftEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimPartnerEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DLevelUpEvent {
  export type InputTuple = [user: AddressLike, newDLevel: BigNumberish];
  export type OutputTuple = [user: string, newDLevel: bigint];
  export interface OutputObject {
    user: string;
    newDLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LevelUpEvent {
  export type InputTuple = [user: AddressLike, newLevel: BigNumberish];
  export type OutputTuple = [user: string, newLevel: bigint];
  export interface OutputObject {
    user: string;
    newLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LineQualifiedEvent {
  export type InputTuple = [user: AddressLike, lineCount: BigNumberish];
  export type OutputTuple = [user: string, lineCount: bigint];
  export interface OutputObject {
    user: string;
    lineCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [newPrice: BigNumberish];
  export type OutputTuple = [newPrice: bigint];
  export interface OutputObject {
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegisterEvent {
  export type InputTuple = [user: AddressLike, referrer: AddressLike];
  export type OutputTuple = [user: string, referrer: string];
  export interface OutputObject {
    user: string;
    referrer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemovePartnerEvent {
  export type InputTuple = [partner: AddressLike];
  export type OutputTuple = [partner: string];
  export interface OutputObject {
    partner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RestrictAddressEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeDQEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    period: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, period: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    period: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapBEP20ForDQEvent {
  export type InputTuple = [
    user: AddressLike,
    tokenAmount: BigNumberish,
    dqAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    tokenAmount: bigint,
    dqAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    tokenAmount: bigint;
    dqAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapDQForBEP20Event {
  export type InputTuple = [
    user: AddressLike,
    dqAmount: BigNumberish,
    tokenAmount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    dqAmount: bigint,
    tokenAmount: bigint,
    fee: bigint
  ];
  export interface OutputObject {
    user: string;
    dqAmount: bigint;
    tokenAmount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnrestrictAddressEvent {
  export type InputTuple = [user: AddressLike];
  export type OutputTuple = [user: string];
  export interface OutputObject {
    user: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakeDQEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    period: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, period: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    period: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, fee: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DQProject extends BaseContract {
  connect(runner?: ContractRunner | null): DQProject;
  waitForDeployment(): Promise<this>;

  interface: DQProjectInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BEP20_TOKEN: TypedContractMethod<[], [string], "view">;

  BLACKHOLE: TypedContractMethod<[], [string], "view">;

  BURN_DECREMENT: TypedContractMethod<[], [bigint], "view">;

  INVEST_MAX_FINAL: TypedContractMethod<[], [bigint], "view">;

  INVEST_MAX_START: TypedContractMethod<[], [bigint], "view">;

  INVEST_MAX_STEP: TypedContractMethod<[], [bigint], "view">;

  INVEST_MIN: TypedContractMethod<[], [bigint], "view">;

  MIN_BURN_RATE: TypedContractMethod<[], [bigint], "view">;

  PHASE_DURATION: TypedContractMethod<[], [bigint], "view">;

  addPartner: TypedContractMethod<
    [_partner: AddressLike],
    [void],
    "nonpayable"
  >;

  addPartnerBatch: TypedContractMethod<
    [_partners: AddressLike[]],
    [void],
    "nonpayable"
  >;

  adminWithdrawBEP20: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  adminWithdrawBNB: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  adminWithdrawDQ: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  allUsers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  blockMining: TypedContractMethod<[], [void], "nonpayable">;

  burnRate: TypedContractMethod<[], [bigint], "view">;

  buyNode: TypedContractMethod<[_type: BigNumberish], [void], "nonpayable">;

  canDeposit: TypedContractMethod<[_user: AddressLike], [boolean], "view">;

  checkNodeQualified: TypedContractMethod<
    [_user: AddressLike],
    [
      [boolean, bigint, bigint] & {
        qualified: boolean;
        currentLines: bigint;
        requiredLines: bigint;
      }
    ],
    "view"
  >;

  claimDTeam: TypedContractMethod<[], [void], "nonpayable">;

  claimLp: TypedContractMethod<[], [void], "nonpayable">;

  claimNft: TypedContractMethod<[], [void], "nonpayable">;

  claimPartner: TypedContractMethod<[], [void], "nonpayable">;

  dAccPerShare: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  dRewardDebt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  dThresholds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  dTotalUsers: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  dailyReleaseRate: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  dqCard: TypedContractMethod<[], [string], "view">;

  dqPrice: TypedContractMethod<[], [bigint], "view">;

  dqToken: TypedContractMethod<[], [string], "view">;

  dynamicPool: TypedContractMethod<[], [bigint], "view">;

  feePool: TypedContractMethod<[], [bigint], "view">;

  foundationWallet: TypedContractMethod<[], [string], "view">;

  getBEP20Balance: TypedContractMethod<[], [bigint], "view">;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getCurrentMaxInvest: TypedContractMethod<[], [bigint], "view">;

  getNodeInfo: TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        cardType: bigint;
        cardCount: bigint;
        qualifiedLines: bigint;
        requiredLines: bigint;
        isQualified: boolean;
      }
    ],
    "view"
  >;

  getPartnerCount: TypedContractMethod<[], [bigint], "view">;

  getPrice: TypedContractMethod<[], [bigint], "view">;

  getRestrictedCount: TypedContractMethod<[], [bigint], "view">;

  getSingleStake: TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;

  getUser: TypedContractMethod<
    [_user: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        boolean
      ] & {
        referrer: string;
        directCount: bigint;
        level: bigint;
        dLevel: bigint;
        totalInvest: bigint;
        teamInvest: bigint;
        energy: bigint;
        directSales: bigint;
        hasNode: boolean;
        hasDeposited: boolean;
        activeLineCount: bigint;
        restricted: boolean;
      }
    ],
    "view"
  >;

  insurancePool: TypedContractMethod<[], [bigint], "view">;

  isPartnerWhite: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lastBlockTime: TypedContractMethod<[], [bigint], "view">;

  lastBlockTimeV2: TypedContractMethod<[], [bigint], "view">;

  levelRates: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  lpAccPerShare: TypedContractMethod<[], [bigint], "view">;

  lpPool: TypedContractMethod<[], [bigint], "view">;

  nftAccPerShare: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  nftRewardDebtAcc: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  operationPool: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  partnerAccPerShare: TypedContractMethod<[], [bigint], "view">;

  partnerDebt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  partnerDqAccPerShare: TypedContractMethod<[], [bigint], "view">;

  partnerWhiteList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  register: TypedContractMethod<[_referrer: AddressLike], [void], "nonpayable">;

  removePartner: TypedContractMethod<
    [_partner: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  restrictAddress: TypedContractMethod<
    [_user: AddressLike],
    [void],
    "nonpayable"
  >;

  restrictAddressBatch: TypedContractMethod<
    [_users: AddressLike[]],
    [void],
    "nonpayable"
  >;

  restrictedAddresses: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  restrictedDebt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setFoundationWallet: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setPrice: TypedContractMethod<
    [_newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  singleStakes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  stakeDQ: TypedContractMethod<
    [amount: BigNumberish, periodIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakeFeeAccPerShare: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  stakePeriods: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  stakeRates: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  startTime: TypedContractMethod<[], [bigint], "view">;

  swapBEP20ForDQ: TypedContractMethod<
    [tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  swapDQForBEP20: TypedContractMethod<
    [dqAmount: BigNumberish, minOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  totalLPShares: TypedContractMethod<[], [bigint], "view">;

  totalRestrictedCount: TypedContractMethod<[], [bigint], "view">;

  totalSingleStaked: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unrestrictAddress: TypedContractMethod<
    [_user: AddressLike],
    [void],
    "nonpayable"
  >;

  unstakeDQ: TypedContractMethod<
    [periodIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [dqAmount: BigNumberish, minOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BEP20_TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BLACKHOLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BURN_DECREMENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INVEST_MAX_FINAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INVEST_MAX_START"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INVEST_MAX_STEP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INVEST_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BURN_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PHASE_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addPartner"
  ): TypedContractMethod<[_partner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addPartnerBatch"
  ): TypedContractMethod<[_partners: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminWithdrawBEP20"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminWithdrawBNB"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminWithdrawDQ"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allUsers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "blockMining"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "burnRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyNode"
  ): TypedContractMethod<[_type: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canDeposit"
  ): TypedContractMethod<[_user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkNodeQualified"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [boolean, bigint, bigint] & {
        qualified: boolean;
        currentLines: bigint;
        requiredLines: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimDTeam"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimLp"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimNft"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimPartner"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dAccPerShare"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "dRewardDebt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "dThresholds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "dTotalUsers"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyReleaseRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dqCard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dqPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dqToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dynamicPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feePool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "foundationWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBEP20Balance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentMaxInvest"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNodeInfo"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint, bigint, boolean] & {
        cardType: bigint;
        cardCount: bigint;
        qualifiedLines: bigint;
        requiredLines: bigint;
        isQualified: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPartnerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRestrictedCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSingleStake"
  ): TypedContractMethod<[_user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint,
        boolean
      ] & {
        referrer: string;
        directCount: bigint;
        level: bigint;
        dLevel: bigint;
        totalInvest: bigint;
        teamInvest: bigint;
        energy: bigint;
        directSales: bigint;
        hasNode: boolean;
        hasDeposited: boolean;
        activeLineCount: bigint;
        restricted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "insurancePool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isPartnerWhite"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastBlockTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lastBlockTimeV2"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "levelRates"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpAccPerShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nftAccPerShare"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "nftRewardDebtAcc"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "operationPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "partnerAccPerShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "partnerDebt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "partnerDqAccPerShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "partnerWhiteList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[_referrer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removePartner"
  ): TypedContractMethod<[_partner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "restrictAddress"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "restrictAddressBatch"
  ): TypedContractMethod<[_users: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "restrictedAddresses"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "restrictedDebt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setFoundationWallet"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPrice"
  ): TypedContractMethod<[_newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "singleStakes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakeDQ"
  ): TypedContractMethod<
    [amount: BigNumberish, periodIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeFeeAccPerShare"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakePeriods"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakeRates"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "startTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "swapBEP20ForDQ"
  ): TypedContractMethod<[tokenAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "swapDQForBEP20"
  ): TypedContractMethod<
    [dqAmount: BigNumberish, minOut: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalLPShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalRestrictedCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSingleStaked"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unrestrictAddress"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeDQ"
  ): TypedContractMethod<[periodIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [dqAmount: BigNumberish, minOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AddPartner"
  ): TypedContractEvent<
    AddPartnerEvent.InputTuple,
    AddPartnerEvent.OutputTuple,
    AddPartnerEvent.OutputObject
  >;
  getEvent(
    key: "BlockMining"
  ): TypedContractEvent<
    BlockMiningEvent.InputTuple,
    BlockMiningEvent.OutputTuple,
    BlockMiningEvent.OutputObject
  >;
  getEvent(
    key: "BuyNode"
  ): TypedContractEvent<
    BuyNodeEvent.InputTuple,
    BuyNodeEvent.OutputTuple,
    BuyNodeEvent.OutputObject
  >;
  getEvent(
    key: "ClaimDTeam"
  ): TypedContractEvent<
    ClaimDTeamEvent.InputTuple,
    ClaimDTeamEvent.OutputTuple,
    ClaimDTeamEvent.OutputObject
  >;
  getEvent(
    key: "ClaimLp"
  ): TypedContractEvent<
    ClaimLpEvent.InputTuple,
    ClaimLpEvent.OutputTuple,
    ClaimLpEvent.OutputObject
  >;
  getEvent(
    key: "ClaimNft"
  ): TypedContractEvent<
    ClaimNftEvent.InputTuple,
    ClaimNftEvent.OutputTuple,
    ClaimNftEvent.OutputObject
  >;
  getEvent(
    key: "ClaimPartner"
  ): TypedContractEvent<
    ClaimPartnerEvent.InputTuple,
    ClaimPartnerEvent.OutputTuple,
    ClaimPartnerEvent.OutputObject
  >;
  getEvent(
    key: "DLevelUp"
  ): TypedContractEvent<
    DLevelUpEvent.InputTuple,
    DLevelUpEvent.OutputTuple,
    DLevelUpEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "LevelUp"
  ): TypedContractEvent<
    LevelUpEvent.InputTuple,
    LevelUpEvent.OutputTuple,
    LevelUpEvent.OutputObject
  >;
  getEvent(
    key: "LineQualified"
  ): TypedContractEvent<
    LineQualifiedEvent.InputTuple,
    LineQualifiedEvent.OutputTuple,
    LineQualifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Register"
  ): TypedContractEvent<
    RegisterEvent.InputTuple,
    RegisterEvent.OutputTuple,
    RegisterEvent.OutputObject
  >;
  getEvent(
    key: "RemovePartner"
  ): TypedContractEvent<
    RemovePartnerEvent.InputTuple,
    RemovePartnerEvent.OutputTuple,
    RemovePartnerEvent.OutputObject
  >;
  getEvent(
    key: "RestrictAddress"
  ): TypedContractEvent<
    RestrictAddressEvent.InputTuple,
    RestrictAddressEvent.OutputTuple,
    RestrictAddressEvent.OutputObject
  >;
  getEvent(
    key: "StakeDQ"
  ): TypedContractEvent<
    StakeDQEvent.InputTuple,
    StakeDQEvent.OutputTuple,
    StakeDQEvent.OutputObject
  >;
  getEvent(
    key: "SwapBEP20ForDQ"
  ): TypedContractEvent<
    SwapBEP20ForDQEvent.InputTuple,
    SwapBEP20ForDQEvent.OutputTuple,
    SwapBEP20ForDQEvent.OutputObject
  >;
  getEvent(
    key: "SwapDQForBEP20"
  ): TypedContractEvent<
    SwapDQForBEP20Event.InputTuple,
    SwapDQForBEP20Event.OutputTuple,
    SwapDQForBEP20Event.OutputObject
  >;
  getEvent(
    key: "UnrestrictAddress"
  ): TypedContractEvent<
    UnrestrictAddressEvent.InputTuple,
    UnrestrictAddressEvent.OutputTuple,
    UnrestrictAddressEvent.OutputObject
  >;
  getEvent(
    key: "UnstakeDQ"
  ): TypedContractEvent<
    UnstakeDQEvent.InputTuple,
    UnstakeDQEvent.OutputTuple,
    UnstakeDQEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;

  filters: {
    "AddPartner(address)": TypedContractEvent<
      AddPartnerEvent.InputTuple,
      AddPartnerEvent.OutputTuple,
      AddPartnerEvent.OutputObject
    >;
    AddPartner: TypedContractEvent<
      AddPartnerEvent.InputTuple,
      AddPartnerEvent.OutputTuple,
      AddPartnerEvent.OutputObject
    >;

    "BlockMining(uint256,uint256,uint256)": TypedContractEvent<
      BlockMiningEvent.InputTuple,
      BlockMiningEvent.OutputTuple,
      BlockMiningEvent.OutputObject
    >;
    BlockMining: TypedContractEvent<
      BlockMiningEvent.InputTuple,
      BlockMiningEvent.OutputTuple,
      BlockMiningEvent.OutputObject
    >;

    "BuyNode(address,uint256,uint256)": TypedContractEvent<
      BuyNodeEvent.InputTuple,
      BuyNodeEvent.OutputTuple,
      BuyNodeEvent.OutputObject
    >;
    BuyNode: TypedContractEvent<
      BuyNodeEvent.InputTuple,
      BuyNodeEvent.OutputTuple,
      BuyNodeEvent.OutputObject
    >;

    "ClaimDTeam(address,uint256)": TypedContractEvent<
      ClaimDTeamEvent.InputTuple,
      ClaimDTeamEvent.OutputTuple,
      ClaimDTeamEvent.OutputObject
    >;
    ClaimDTeam: TypedContractEvent<
      ClaimDTeamEvent.InputTuple,
      ClaimDTeamEvent.OutputTuple,
      ClaimDTeamEvent.OutputObject
    >;

    "ClaimLp(address,uint256)": TypedContractEvent<
      ClaimLpEvent.InputTuple,
      ClaimLpEvent.OutputTuple,
      ClaimLpEvent.OutputObject
    >;
    ClaimLp: TypedContractEvent<
      ClaimLpEvent.InputTuple,
      ClaimLpEvent.OutputTuple,
      ClaimLpEvent.OutputObject
    >;

    "ClaimNft(address,uint256)": TypedContractEvent<
      ClaimNftEvent.InputTuple,
      ClaimNftEvent.OutputTuple,
      ClaimNftEvent.OutputObject
    >;
    ClaimNft: TypedContractEvent<
      ClaimNftEvent.InputTuple,
      ClaimNftEvent.OutputTuple,
      ClaimNftEvent.OutputObject
    >;

    "ClaimPartner(address,uint256)": TypedContractEvent<
      ClaimPartnerEvent.InputTuple,
      ClaimPartnerEvent.OutputTuple,
      ClaimPartnerEvent.OutputObject
    >;
    ClaimPartner: TypedContractEvent<
      ClaimPartnerEvent.InputTuple,
      ClaimPartnerEvent.OutputTuple,
      ClaimPartnerEvent.OutputObject
    >;

    "DLevelUp(address,uint8)": TypedContractEvent<
      DLevelUpEvent.InputTuple,
      DLevelUpEvent.OutputTuple,
      DLevelUpEvent.OutputObject
    >;
    DLevelUp: TypedContractEvent<
      DLevelUpEvent.InputTuple,
      DLevelUpEvent.OutputTuple,
      DLevelUpEvent.OutputObject
    >;

    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "LevelUp(address,uint8)": TypedContractEvent<
      LevelUpEvent.InputTuple,
      LevelUpEvent.OutputTuple,
      LevelUpEvent.OutputObject
    >;
    LevelUp: TypedContractEvent<
      LevelUpEvent.InputTuple,
      LevelUpEvent.OutputTuple,
      LevelUpEvent.OutputObject
    >;

    "LineQualified(address,uint256)": TypedContractEvent<
      LineQualifiedEvent.InputTuple,
      LineQualifiedEvent.OutputTuple,
      LineQualifiedEvent.OutputObject
    >;
    LineQualified: TypedContractEvent<
      LineQualifiedEvent.InputTuple,
      LineQualifiedEvent.OutputTuple,
      LineQualifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceUpdated(uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "Register(address,address)": TypedContractEvent<
      RegisterEvent.InputTuple,
      RegisterEvent.OutputTuple,
      RegisterEvent.OutputObject
    >;
    Register: TypedContractEvent<
      RegisterEvent.InputTuple,
      RegisterEvent.OutputTuple,
      RegisterEvent.OutputObject
    >;

    "RemovePartner(address)": TypedContractEvent<
      RemovePartnerEvent.InputTuple,
      RemovePartnerEvent.OutputTuple,
      RemovePartnerEvent.OutputObject
    >;
    RemovePartner: TypedContractEvent<
      RemovePartnerEvent.InputTuple,
      RemovePartnerEvent.OutputTuple,
      RemovePartnerEvent.OutputObject
    >;

    "RestrictAddress(address)": TypedContractEvent<
      RestrictAddressEvent.InputTuple,
      RestrictAddressEvent.OutputTuple,
      RestrictAddressEvent.OutputObject
    >;
    RestrictAddress: TypedContractEvent<
      RestrictAddressEvent.InputTuple,
      RestrictAddressEvent.OutputTuple,
      RestrictAddressEvent.OutputObject
    >;

    "StakeDQ(address,uint256,uint256)": TypedContractEvent<
      StakeDQEvent.InputTuple,
      StakeDQEvent.OutputTuple,
      StakeDQEvent.OutputObject
    >;
    StakeDQ: TypedContractEvent<
      StakeDQEvent.InputTuple,
      StakeDQEvent.OutputTuple,
      StakeDQEvent.OutputObject
    >;

    "SwapBEP20ForDQ(address,uint256,uint256)": TypedContractEvent<
      SwapBEP20ForDQEvent.InputTuple,
      SwapBEP20ForDQEvent.OutputTuple,
      SwapBEP20ForDQEvent.OutputObject
    >;
    SwapBEP20ForDQ: TypedContractEvent<
      SwapBEP20ForDQEvent.InputTuple,
      SwapBEP20ForDQEvent.OutputTuple,
      SwapBEP20ForDQEvent.OutputObject
    >;

    "SwapDQForBEP20(address,uint256,uint256,uint256)": TypedContractEvent<
      SwapDQForBEP20Event.InputTuple,
      SwapDQForBEP20Event.OutputTuple,
      SwapDQForBEP20Event.OutputObject
    >;
    SwapDQForBEP20: TypedContractEvent<
      SwapDQForBEP20Event.InputTuple,
      SwapDQForBEP20Event.OutputTuple,
      SwapDQForBEP20Event.OutputObject
    >;

    "UnrestrictAddress(address)": TypedContractEvent<
      UnrestrictAddressEvent.InputTuple,
      UnrestrictAddressEvent.OutputTuple,
      UnrestrictAddressEvent.OutputObject
    >;
    UnrestrictAddress: TypedContractEvent<
      UnrestrictAddressEvent.InputTuple,
      UnrestrictAddressEvent.OutputTuple,
      UnrestrictAddressEvent.OutputObject
    >;

    "UnstakeDQ(address,uint256,uint256)": TypedContractEvent<
      UnstakeDQEvent.InputTuple,
      UnstakeDQEvent.OutputTuple,
      UnstakeDQEvent.OutputObject
    >;
    UnstakeDQ: TypedContractEvent<
      UnstakeDQEvent.InputTuple,
      UnstakeDQEvent.OutputTuple,
      UnstakeDQEvent.OutputObject
    >;

    "Withdraw(address,uint256,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
