/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DQMCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DAILY_LIMIT"
      | "DAO"
      | "DAO_RATE"
      | "DIRECT_RATE"
      | "ENERGY_MUL"
      | "FACTORY"
      | "INS"
      | "INS_RATE"
      | "INVEST_MIN"
      | "MAX_LIMIT"
      | "OP"
      | "OP_RATE"
      | "OWNER"
      | "ROUTER"
      | "SOL"
      | "USDT"
      | "VERSION"
      | "WBNB"
      | "WITHDRAW_FEE"
      | "adminAddEnergy"
      | "adminContract"
      | "adminSetEnergy"
      | "adminSubEnergy"
      | "advancePhase"
      | "allUsers"
      | "batchSetDepositWhiteList"
      | "changeReferrer"
      | "currentDepositLimit"
      | "currentPhase"
      | "dailyDeposit"
      | "deposit"
      | "depositForUser"
      | "depositWhiteList"
      | "dqCard"
      | "dqToken"
      | "feeAddr"
      | "fixedNodeAddr"
      | "foundation"
      | "getAllUsers"
      | "getAllUsersCount"
      | "getAvailableEnergy"
      | "getCurrentLimit"
      | "getEnergyInfo"
      | "getUser"
      | "getUserChildren"
      | "getUserTotalInvest"
      | "importUserRelation"
      | "importUsers"
      | "isBlacklisted"
      | "lpSlippage"
      | "manualAddLP"
      | "migratorContract"
      | "nodeUSDTReceiver"
      | "partnerAddr"
      | "pool"
      | "register"
      | "sellDQ"
      | "sellFeeReceiver"
      | "setAddresses"
      | "setAdminContract"
      | "setBlacklisted"
      | "setDAO"
      | "setDepositLimit"
      | "setDepositWhiteList"
      | "setINS"
      | "setMigratorContract"
      | "setOP"
      | "setPartnerAddr"
      | "setPhase"
      | "setPool"
      | "setSellFeeReceiver"
      | "setSlippage"
      | "setUserLevel"
      | "stakeContract"
      | "startTime"
      | "swapSlippage"
      | "totalEnergy"
      | "totalInvested"
      | "totalLPAdded"
      | "transferSOLToUser"
      | "useEnergy"
      | "userEnergy"
      | "userEnergyUsed"
      | "withdrawSOL"
      | "withdrawToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressesUpdated"
      | "DQSold"
      | "Deposit"
      | "EnergyAdded"
      | "LPAdded"
      | "PhaseAdvanced"
      | "PoolSet"
      | "ReferrerChanged"
      | "Register"
      | "SlippageUpdated"
      | "SwapAndAddLP"
      | "TokenWithdrawn"
      | "UserLevelSet"
      | "WithdrawSOL"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DAILY_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DAO", values?: undefined): string;
  encodeFunctionData(functionFragment: "DAO_RATE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DIRECT_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ENERGY_MUL",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "FACTORY", values?: undefined): string;
  encodeFunctionData(functionFragment: "INS", values?: undefined): string;
  encodeFunctionData(functionFragment: "INS_RATE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "INVEST_MIN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MAX_LIMIT", values?: undefined): string;
  encodeFunctionData(functionFragment: "OP", values?: undefined): string;
  encodeFunctionData(functionFragment: "OP_RATE", values?: undefined): string;
  encodeFunctionData(functionFragment: "OWNER", values?: undefined): string;
  encodeFunctionData(functionFragment: "ROUTER", values?: undefined): string;
  encodeFunctionData(functionFragment: "SOL", values?: undefined): string;
  encodeFunctionData(functionFragment: "USDT", values?: undefined): string;
  encodeFunctionData(functionFragment: "VERSION", values?: undefined): string;
  encodeFunctionData(functionFragment: "WBNB", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "WITHDRAW_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminAddEnergy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "adminSetEnergy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminSubEnergy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "advancePhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allUsers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetDepositWhiteList",
    values: [AddressLike[], boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "changeReferrer",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "currentDepositLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "currentPhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyDeposit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositForUser",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWhiteList",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "dqCard", values?: undefined): string;
  encodeFunctionData(functionFragment: "dqToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "feeAddr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fixedNodeAddr",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "foundation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAllUsers",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllUsersCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAvailableEnergy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEnergyInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserChildren",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserTotalInvest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "importUserRelation",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "importUsers",
    values: [AddressLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lpSlippage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "manualAddLP",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "migratorContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nodeUSDTReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "partnerAddr",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "pool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sellDQ",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "sellFeeReceiver",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAddresses",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAdminContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBlacklisted",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setDAO", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setDepositLimit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDepositWhiteList",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(functionFragment: "setINS", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setMigratorContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setOP", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "setPartnerAddr",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPhase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPool",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSellFeeReceiver",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSlippage",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setUserLevel",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "startTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "swapSlippage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalEnergy",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalInvested",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalLPAdded",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferSOLToUser",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "useEnergy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userEnergy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "userEnergyUsed",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawSOL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawToken",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "DAILY_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "DAO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DAO_RATE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DIRECT_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ENERGY_MUL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FACTORY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "INS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "INS_RATE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "INVEST_MIN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MAX_LIMIT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "OP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "OP_RATE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "OWNER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ROUTER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SOL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "USDT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "VERSION", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "WBNB", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "WITHDRAW_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminAddEnergy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminSetEnergy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminSubEnergy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "advancePhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchSetDepositWhiteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "changeReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentDepositLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositForUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositWhiteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dqCard", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dqToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeAddr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fixedNodeAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "foundation", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllUsersCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAvailableEnergy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEnergyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserChildren",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserTotalInvest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "importUserRelation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "importUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpSlippage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manualAddLP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "migratorContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nodeUSDTReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "partnerAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sellDQ", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sellFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAddresses",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAdminContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setDAO", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setDepositLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDepositWhiteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setINS", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMigratorContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPartnerAddr",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPhase", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setSellFeeReceiver",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSlippage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setUserLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapSlippage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalEnergy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalInvested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalLPAdded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferSOLToUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "useEnergy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "userEnergy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userEnergyUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawSOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawToken",
    data: BytesLike
  ): Result;
}

export namespace AddressesUpdatedEvent {
  export type InputTuple = [
    dqToken: AddressLike,
    dqCard: AddressLike,
    stakeContract: AddressLike
  ];
  export type OutputTuple = [
    dqToken: string,
    dqCard: string,
    stakeContract: string
  ];
  export interface OutputObject {
    dqToken: string;
    dqCard: string;
    stakeContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DQSoldEvent {
  export type InputTuple = [
    seller: AddressLike,
    dqAmount: BigNumberish,
    swapAmount: BigNumberish,
    minSolOut: BigNumberish
  ];
  export type OutputTuple = [
    seller: string,
    dqAmount: bigint,
    swapAmount: bigint,
    minSolOut: bigint
  ];
  export interface OutputObject {
    seller: string;
    dqAmount: bigint;
    swapAmount: bigint;
    minSolOut: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    lpAmount: BigNumberish,
    energy: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    lpAmount: bigint,
    energy: bigint
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    lpAmount: bigint;
    energy: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EnergyAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    totalEnergy: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, totalEnergy: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    totalEnergy: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LPAddedEvent {
  export type InputTuple = [
    user: AddressLike,
    solAmount: BigNumberish,
    dqAmount: BigNumberish,
    lpAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    solAmount: bigint,
    dqAmount: bigint,
    lpAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    solAmount: bigint;
    dqAmount: bigint;
    lpAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PhaseAdvancedEvent {
  export type InputTuple = [newPhase: BigNumberish, newLimit: BigNumberish];
  export type OutputTuple = [newPhase: bigint, newLimit: bigint];
  export interface OutputObject {
    newPhase: bigint;
    newLimit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PoolSetEvent {
  export type InputTuple = [pool: AddressLike];
  export type OutputTuple = [pool: string];
  export interface OutputObject {
    pool: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReferrerChangedEvent {
  export type InputTuple = [
    user: AddressLike,
    oldReferrer: AddressLike,
    newReferrer: AddressLike
  ];
  export type OutputTuple = [
    user: string,
    oldReferrer: string,
    newReferrer: string
  ];
  export interface OutputObject {
    user: string;
    oldReferrer: string;
    newReferrer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegisterEvent {
  export type InputTuple = [user: AddressLike, referrer: AddressLike];
  export type OutputTuple = [user: string, referrer: string];
  export interface OutputObject {
    user: string;
    referrer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlippageUpdatedEvent {
  export type InputTuple = [
    swapSlippage: BigNumberish,
    lpSlippage: BigNumberish
  ];
  export type OutputTuple = [swapSlippage: bigint, lpSlippage: bigint];
  export interface OutputObject {
    swapSlippage: bigint;
    lpSlippage: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapAndAddLPEvent {
  export type InputTuple = [
    user: AddressLike,
    solAmount: BigNumberish,
    dqAmount: BigNumberish,
    lpAmount: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    solAmount: bigint,
    dqAmount: bigint,
    lpAmount: bigint
  ];
  export interface OutputObject {
    user: string;
    solAmount: bigint;
    dqAmount: bigint;
    lpAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenWithdrawnEvent {
  export type InputTuple = [
    token: AddressLike,
    to: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [token: string, to: string, amount: bigint];
  export interface OutputObject {
    token: string;
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UserLevelSetEvent {
  export type InputTuple = [user: AddressLike, level: BigNumberish];
  export type OutputTuple = [user: string, level: bigint];
  export interface OutputObject {
    user: string;
    level: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawSOLEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, fee: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DQMCore extends BaseContract {
  connect(runner?: ContractRunner | null): DQMCore;
  waitForDeployment(): Promise<this>;

  interface: DQMCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DAILY_LIMIT: TypedContractMethod<[], [bigint], "view">;

  DAO: TypedContractMethod<[], [string], "view">;

  DAO_RATE: TypedContractMethod<[], [bigint], "view">;

  DIRECT_RATE: TypedContractMethod<[], [bigint], "view">;

  ENERGY_MUL: TypedContractMethod<[], [bigint], "view">;

  FACTORY: TypedContractMethod<[], [string], "view">;

  INS: TypedContractMethod<[], [string], "view">;

  INS_RATE: TypedContractMethod<[], [bigint], "view">;

  INVEST_MIN: TypedContractMethod<[], [bigint], "view">;

  MAX_LIMIT: TypedContractMethod<[], [bigint], "view">;

  OP: TypedContractMethod<[], [string], "view">;

  OP_RATE: TypedContractMethod<[], [bigint], "view">;

  OWNER: TypedContractMethod<[], [string], "view">;

  ROUTER: TypedContractMethod<[], [string], "view">;

  SOL: TypedContractMethod<[], [string], "view">;

  USDT: TypedContractMethod<[], [string], "view">;

  VERSION: TypedContractMethod<[], [bigint], "view">;

  WBNB: TypedContractMethod<[], [string], "view">;

  WITHDRAW_FEE: TypedContractMethod<[], [bigint], "view">;

  adminAddEnergy: TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  adminContract: TypedContractMethod<[], [string], "view">;

  adminSetEnergy: TypedContractMethod<
    [_user: AddressLike, _energy: BigNumberish],
    [void],
    "nonpayable"
  >;

  adminSubEnergy: TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  advancePhase: TypedContractMethod<[], [void], "nonpayable">;

  allUsers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  batchSetDepositWhiteList: TypedContractMethod<
    [_users: AddressLike[], _status: boolean],
    [void],
    "nonpayable"
  >;

  changeReferrer: TypedContractMethod<
    [_user: AddressLike, _newReferrer: AddressLike],
    [void],
    "nonpayable"
  >;

  currentDepositLimit: TypedContractMethod<[], [bigint], "view">;

  currentPhase: TypedContractMethod<[], [bigint], "view">;

  dailyDeposit: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  deposit: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  depositForUser: TypedContractMethod<
    [_user: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositWhiteList: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  dqCard: TypedContractMethod<[], [string], "view">;

  dqToken: TypedContractMethod<[], [string], "view">;

  feeAddr: TypedContractMethod<[], [string], "view">;

  fixedNodeAddr: TypedContractMethod<[], [string], "view">;

  foundation: TypedContractMethod<[], [string], "view">;

  getAllUsers: TypedContractMethod<
    [_start: BigNumberish, _end: BigNumberish],
    [string[]],
    "view"
  >;

  getAllUsersCount: TypedContractMethod<[], [bigint], "view">;

  getAvailableEnergy: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  getCurrentLimit: TypedContractMethod<[], [bigint], "view">;

  getEnergyInfo: TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalEnergy: bigint;
        usedEnergy: bigint;
        availableEnergy: bigint;
      }
    ],
    "view"
  >;

  getUser: TypedContractMethod<
    [_user: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint] & {
        referrer: string;
        directCount: bigint;
        level: bigint;
        totalInvest: bigint;
        childrenCount: bigint;
      }
    ],
    "view"
  >;

  getUserChildren: TypedContractMethod<
    [_user: AddressLike, _start: BigNumberish, _end: BigNumberish],
    [string[]],
    "view"
  >;

  getUserTotalInvest: TypedContractMethod<
    [_user: AddressLike],
    [bigint],
    "view"
  >;

  importUserRelation: TypedContractMethod<
    [_user: AddressLike, _referrer: AddressLike],
    [void],
    "nonpayable"
  >;

  importUsers: TypedContractMethod<
    [_users: AddressLike[], _referrers: AddressLike[]],
    [void],
    "nonpayable"
  >;

  isBlacklisted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lpSlippage: TypedContractMethod<[], [bigint], "view">;

  manualAddLP: TypedContractMethod<
    [_user: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  migratorContract: TypedContractMethod<[], [string], "view">;

  nodeUSDTReceiver: TypedContractMethod<[], [string], "view">;

  partnerAddr: TypedContractMethod<[], [string], "view">;

  pool: TypedContractMethod<[], [string], "view">;

  register: TypedContractMethod<[_referrer: AddressLike], [void], "nonpayable">;

  sellDQ: TypedContractMethod<[_dqAmount: BigNumberish], [void], "nonpayable">;

  sellFeeReceiver: TypedContractMethod<[], [string], "view">;

  setAddresses: TypedContractMethod<
    [_dqToken: AddressLike, _dqCard: AddressLike, _stakeContract: AddressLike],
    [void],
    "nonpayable"
  >;

  setAdminContract: TypedContractMethod<
    [_admin: AddressLike],
    [void],
    "nonpayable"
  >;

  setBlacklisted: TypedContractMethod<
    [_user: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  setDAO: TypedContractMethod<[_dao: AddressLike], [void], "nonpayable">;

  setDepositLimit: TypedContractMethod<
    [_limit: BigNumberish],
    [void],
    "nonpayable"
  >;

  setDepositWhiteList: TypedContractMethod<
    [_user: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  setINS: TypedContractMethod<[_ins: AddressLike], [void], "nonpayable">;

  setMigratorContract: TypedContractMethod<
    [_migrator: AddressLike],
    [void],
    "nonpayable"
  >;

  setOP: TypedContractMethod<[_op: AddressLike], [void], "nonpayable">;

  setPartnerAddr: TypedContractMethod<
    [_addr: AddressLike],
    [void],
    "nonpayable"
  >;

  setPhase: TypedContractMethod<[_phase: BigNumberish], [void], "nonpayable">;

  setPool: TypedContractMethod<[_pool: AddressLike], [void], "nonpayable">;

  setSellFeeReceiver: TypedContractMethod<
    [_addr: AddressLike],
    [void],
    "nonpayable"
  >;

  setSlippage: TypedContractMethod<
    [_swapSlippage: BigNumberish, _lpSlippage: BigNumberish],
    [void],
    "nonpayable"
  >;

  setUserLevel: TypedContractMethod<
    [_user: AddressLike, _level: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakeContract: TypedContractMethod<[], [string], "view">;

  startTime: TypedContractMethod<[], [bigint], "view">;

  swapSlippage: TypedContractMethod<[], [bigint], "view">;

  totalEnergy: TypedContractMethod<[], [bigint], "view">;

  totalInvested: TypedContractMethod<[], [bigint], "view">;

  totalLPAdded: TypedContractMethod<[], [bigint], "view">;

  transferSOLToUser: TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  useEnergy: TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  userEnergy: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  userEnergyUsed: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  withdrawSOL: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawToken: TypedContractMethod<
    [_token: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DAILY_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DAO"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DAO_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DIRECT_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ENERGY_MUL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FACTORY"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INS_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INVEST_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "OP"): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OP_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OWNER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "ROUTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SOL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "USDT"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERSION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "WBNB"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WITHDRAW_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "adminAddEnergy"
  ): TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "adminContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "adminSetEnergy"
  ): TypedContractMethod<
    [_user: AddressLike, _energy: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "adminSubEnergy"
  ): TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "advancePhase"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allUsers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "batchSetDepositWhiteList"
  ): TypedContractMethod<
    [_users: AddressLike[], _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "changeReferrer"
  ): TypedContractMethod<
    [_user: AddressLike, _newReferrer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentDepositLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "currentPhase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyDeposit"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositForUser"
  ): TypedContractMethod<
    [_user: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositWhiteList"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "dqCard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dqToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeAddr"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fixedNodeAddr"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "foundation"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllUsers"
  ): TypedContractMethod<
    [_start: BigNumberish, _end: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllUsersCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAvailableEnergy"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEnergyInfo"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [bigint, bigint, bigint] & {
        totalEnergy: bigint;
        usedEnergy: bigint;
        availableEnergy: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [string, bigint, bigint, bigint, bigint] & {
        referrer: string;
        directCount: bigint;
        level: bigint;
        totalInvest: bigint;
        childrenCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserChildren"
  ): TypedContractMethod<
    [_user: AddressLike, _start: BigNumberish, _end: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserTotalInvest"
  ): TypedContractMethod<[_user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "importUserRelation"
  ): TypedContractMethod<
    [_user: AddressLike, _referrer: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "importUsers"
  ): TypedContractMethod<
    [_users: AddressLike[], _referrers: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isBlacklisted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lpSlippage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "manualAddLP"
  ): TypedContractMethod<
    [_user: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "migratorContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "nodeUSDTReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "partnerAddr"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pool"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[_referrer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellDQ"
  ): TypedContractMethod<[_dqAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellFeeReceiver"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAddresses"
  ): TypedContractMethod<
    [_dqToken: AddressLike, _dqCard: AddressLike, _stakeContract: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAdminContract"
  ): TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBlacklisted"
  ): TypedContractMethod<
    [_user: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDAO"
  ): TypedContractMethod<[_dao: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDepositLimit"
  ): TypedContractMethod<[_limit: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDepositWhiteList"
  ): TypedContractMethod<
    [_user: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setINS"
  ): TypedContractMethod<[_ins: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMigratorContract"
  ): TypedContractMethod<[_migrator: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOP"
  ): TypedContractMethod<[_op: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPartnerAddr"
  ): TypedContractMethod<[_addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPhase"
  ): TypedContractMethod<[_phase: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPool"
  ): TypedContractMethod<[_pool: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSellFeeReceiver"
  ): TypedContractMethod<[_addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSlippage"
  ): TypedContractMethod<
    [_swapSlippage: BigNumberish, _lpSlippage: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setUserLevel"
  ): TypedContractMethod<
    [_user: AddressLike, _level: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakeContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "startTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "swapSlippage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalEnergy"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalInvested"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalLPAdded"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferSOLToUser"
  ): TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "useEnergy"
  ): TypedContractMethod<
    [_user: AddressLike, _amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "userEnergy"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "userEnergyUsed"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawSOL"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawToken"
  ): TypedContractMethod<
    [_token: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AddressesUpdated"
  ): TypedContractEvent<
    AddressesUpdatedEvent.InputTuple,
    AddressesUpdatedEvent.OutputTuple,
    AddressesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "DQSold"
  ): TypedContractEvent<
    DQSoldEvent.InputTuple,
    DQSoldEvent.OutputTuple,
    DQSoldEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "EnergyAdded"
  ): TypedContractEvent<
    EnergyAddedEvent.InputTuple,
    EnergyAddedEvent.OutputTuple,
    EnergyAddedEvent.OutputObject
  >;
  getEvent(
    key: "LPAdded"
  ): TypedContractEvent<
    LPAddedEvent.InputTuple,
    LPAddedEvent.OutputTuple,
    LPAddedEvent.OutputObject
  >;
  getEvent(
    key: "PhaseAdvanced"
  ): TypedContractEvent<
    PhaseAdvancedEvent.InputTuple,
    PhaseAdvancedEvent.OutputTuple,
    PhaseAdvancedEvent.OutputObject
  >;
  getEvent(
    key: "PoolSet"
  ): TypedContractEvent<
    PoolSetEvent.InputTuple,
    PoolSetEvent.OutputTuple,
    PoolSetEvent.OutputObject
  >;
  getEvent(
    key: "ReferrerChanged"
  ): TypedContractEvent<
    ReferrerChangedEvent.InputTuple,
    ReferrerChangedEvent.OutputTuple,
    ReferrerChangedEvent.OutputObject
  >;
  getEvent(
    key: "Register"
  ): TypedContractEvent<
    RegisterEvent.InputTuple,
    RegisterEvent.OutputTuple,
    RegisterEvent.OutputObject
  >;
  getEvent(
    key: "SlippageUpdated"
  ): TypedContractEvent<
    SlippageUpdatedEvent.InputTuple,
    SlippageUpdatedEvent.OutputTuple,
    SlippageUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SwapAndAddLP"
  ): TypedContractEvent<
    SwapAndAddLPEvent.InputTuple,
    SwapAndAddLPEvent.OutputTuple,
    SwapAndAddLPEvent.OutputObject
  >;
  getEvent(
    key: "TokenWithdrawn"
  ): TypedContractEvent<
    TokenWithdrawnEvent.InputTuple,
    TokenWithdrawnEvent.OutputTuple,
    TokenWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "UserLevelSet"
  ): TypedContractEvent<
    UserLevelSetEvent.InputTuple,
    UserLevelSetEvent.OutputTuple,
    UserLevelSetEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawSOL"
  ): TypedContractEvent<
    WithdrawSOLEvent.InputTuple,
    WithdrawSOLEvent.OutputTuple,
    WithdrawSOLEvent.OutputObject
  >;

  filters: {
    "AddressesUpdated(address,address,address)": TypedContractEvent<
      AddressesUpdatedEvent.InputTuple,
      AddressesUpdatedEvent.OutputTuple,
      AddressesUpdatedEvent.OutputObject
    >;
    AddressesUpdated: TypedContractEvent<
      AddressesUpdatedEvent.InputTuple,
      AddressesUpdatedEvent.OutputTuple,
      AddressesUpdatedEvent.OutputObject
    >;

    "DQSold(address,uint256,uint256,uint256)": TypedContractEvent<
      DQSoldEvent.InputTuple,
      DQSoldEvent.OutputTuple,
      DQSoldEvent.OutputObject
    >;
    DQSold: TypedContractEvent<
      DQSoldEvent.InputTuple,
      DQSoldEvent.OutputTuple,
      DQSoldEvent.OutputObject
    >;

    "Deposit(address,uint256,uint256,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "EnergyAdded(address,uint256,uint256)": TypedContractEvent<
      EnergyAddedEvent.InputTuple,
      EnergyAddedEvent.OutputTuple,
      EnergyAddedEvent.OutputObject
    >;
    EnergyAdded: TypedContractEvent<
      EnergyAddedEvent.InputTuple,
      EnergyAddedEvent.OutputTuple,
      EnergyAddedEvent.OutputObject
    >;

    "LPAdded(address,uint256,uint256,uint256)": TypedContractEvent<
      LPAddedEvent.InputTuple,
      LPAddedEvent.OutputTuple,
      LPAddedEvent.OutputObject
    >;
    LPAdded: TypedContractEvent<
      LPAddedEvent.InputTuple,
      LPAddedEvent.OutputTuple,
      LPAddedEvent.OutputObject
    >;

    "PhaseAdvanced(uint256,uint256)": TypedContractEvent<
      PhaseAdvancedEvent.InputTuple,
      PhaseAdvancedEvent.OutputTuple,
      PhaseAdvancedEvent.OutputObject
    >;
    PhaseAdvanced: TypedContractEvent<
      PhaseAdvancedEvent.InputTuple,
      PhaseAdvancedEvent.OutputTuple,
      PhaseAdvancedEvent.OutputObject
    >;

    "PoolSet(address)": TypedContractEvent<
      PoolSetEvent.InputTuple,
      PoolSetEvent.OutputTuple,
      PoolSetEvent.OutputObject
    >;
    PoolSet: TypedContractEvent<
      PoolSetEvent.InputTuple,
      PoolSetEvent.OutputTuple,
      PoolSetEvent.OutputObject
    >;

    "ReferrerChanged(address,address,address)": TypedContractEvent<
      ReferrerChangedEvent.InputTuple,
      ReferrerChangedEvent.OutputTuple,
      ReferrerChangedEvent.OutputObject
    >;
    ReferrerChanged: TypedContractEvent<
      ReferrerChangedEvent.InputTuple,
      ReferrerChangedEvent.OutputTuple,
      ReferrerChangedEvent.OutputObject
    >;

    "Register(address,address)": TypedContractEvent<
      RegisterEvent.InputTuple,
      RegisterEvent.OutputTuple,
      RegisterEvent.OutputObject
    >;
    Register: TypedContractEvent<
      RegisterEvent.InputTuple,
      RegisterEvent.OutputTuple,
      RegisterEvent.OutputObject
    >;

    "SlippageUpdated(uint256,uint256)": TypedContractEvent<
      SlippageUpdatedEvent.InputTuple,
      SlippageUpdatedEvent.OutputTuple,
      SlippageUpdatedEvent.OutputObject
    >;
    SlippageUpdated: TypedContractEvent<
      SlippageUpdatedEvent.InputTuple,
      SlippageUpdatedEvent.OutputTuple,
      SlippageUpdatedEvent.OutputObject
    >;

    "SwapAndAddLP(address,uint256,uint256,uint256)": TypedContractEvent<
      SwapAndAddLPEvent.InputTuple,
      SwapAndAddLPEvent.OutputTuple,
      SwapAndAddLPEvent.OutputObject
    >;
    SwapAndAddLP: TypedContractEvent<
      SwapAndAddLPEvent.InputTuple,
      SwapAndAddLPEvent.OutputTuple,
      SwapAndAddLPEvent.OutputObject
    >;

    "TokenWithdrawn(address,address,uint256)": TypedContractEvent<
      TokenWithdrawnEvent.InputTuple,
      TokenWithdrawnEvent.OutputTuple,
      TokenWithdrawnEvent.OutputObject
    >;
    TokenWithdrawn: TypedContractEvent<
      TokenWithdrawnEvent.InputTuple,
      TokenWithdrawnEvent.OutputTuple,
      TokenWithdrawnEvent.OutputObject
    >;

    "UserLevelSet(address,uint8)": TypedContractEvent<
      UserLevelSetEvent.InputTuple,
      UserLevelSetEvent.OutputTuple,
      UserLevelSetEvent.OutputObject
    >;
    UserLevelSet: TypedContractEvent<
      UserLevelSetEvent.InputTuple,
      UserLevelSetEvent.OutputTuple,
      UserLevelSetEvent.OutputObject
    >;

    "WithdrawSOL(address,uint256,uint256)": TypedContractEvent<
      WithdrawSOLEvent.InputTuple,
      WithdrawSOLEvent.OutputTuple,
      WithdrawSOLEvent.OutputObject
    >;
    WithdrawSOL: TypedContractEvent<
      WithdrawSOLEvent.InputTuple,
      WithdrawSOLEvent.OutputTuple,
      WithdrawSOLEvent.OutputObject
    >;
  };
}
