/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IDQCardAdminInterface extends Interface {
  getFunction(
    nameOrSignature: "setAdminContract" | "setCoreContract" | "setStakeContract"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "setAdminContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setCoreContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakeContract",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "setAdminContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCoreContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakeContract",
    data: BytesLike
  ): Result;
}

export interface IDQCardAdmin extends BaseContract {
  connect(runner?: ContractRunner | null): IDQCardAdmin;
  waitForDeployment(): Promise<this>;

  interface: IDQCardAdminInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  setAdminContract: TypedContractMethod<
    [_addr: AddressLike],
    [void],
    "nonpayable"
  >;

  setCoreContract: TypedContractMethod<
    [_addr: AddressLike],
    [void],
    "nonpayable"
  >;

  setStakeContract: TypedContractMethod<
    [_addr: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "setAdminContract"
  ): TypedContractMethod<[_addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setCoreContract"
  ): TypedContractMethod<[_addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStakeContract"
  ): TypedContractMethod<[_addr: AddressLike], [void], "nonpayable">;

  filters: {};
}
