/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IDQCardInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PRICE_A"
      | "PRICE_B"
      | "PRICE_C"
      | "balanceOf"
      | "cardType"
      | "getCardPrice"
      | "mintByOwner"
      | "tokenOfOwnerByIndex"
      | "totalA"
      | "totalB"
      | "totalC"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "PRICE_A", values?: undefined): string;
  encodeFunctionData(functionFragment: "PRICE_B", values?: undefined): string;
  encodeFunctionData(functionFragment: "PRICE_C", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "cardType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCardPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintByOwner",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenOfOwnerByIndex",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "totalA", values?: undefined): string;
  encodeFunctionData(functionFragment: "totalB", values?: undefined): string;
  encodeFunctionData(functionFragment: "totalC", values?: undefined): string;

  decodeFunctionResult(functionFragment: "PRICE_A", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PRICE_B", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PRICE_C", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "cardType", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCardPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintByOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "tokenOfOwnerByIndex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalB", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "totalC", data: BytesLike): Result;
}

export interface IDQCard extends BaseContract {
  connect(runner?: ContractRunner | null): IDQCard;
  waitForDeployment(): Promise<this>;

  interface: IDQCardInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PRICE_A: TypedContractMethod<[], [bigint], "view">;

  PRICE_B: TypedContractMethod<[], [bigint], "view">;

  PRICE_C: TypedContractMethod<[], [bigint], "view">;

  balanceOf: TypedContractMethod<[owner: AddressLike], [bigint], "view">;

  cardType: TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;

  getCardPrice: TypedContractMethod<[_type: BigNumberish], [bigint], "view">;

  mintByOwner: TypedContractMethod<
    [to: AddressLike, _type: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenOfOwnerByIndex: TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;

  totalA: TypedContractMethod<[], [bigint], "view">;

  totalB: TypedContractMethod<[], [bigint], "view">;

  totalC: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PRICE_A"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_B"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PRICE_C"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[owner: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "cardType"
  ): TypedContractMethod<[tokenId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCardPrice"
  ): TypedContractMethod<[_type: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "mintByOwner"
  ): TypedContractMethod<
    [to: AddressLike, _type: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenOfOwnerByIndex"
  ): TypedContractMethod<
    [owner: AddressLike, index: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "totalA"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalC"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
