/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IDQMiningStakeCoreInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "CLAIM_FEE"
      | "FIXED_NODE"
      | "FOUNDATION"
      | "PARTNER"
      | "coreContract"
      | "dqToken"
      | "getLP"
      | "getLPEquity"
      | "lpAccumulator"
      | "lpDebt"
      | "lpEquityDebt"
      | "totalLP"
      | "totalLPEquitySupply"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "CLAIM_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "FIXED_NODE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FOUNDATION",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "PARTNER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "coreContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "dqToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "getLP", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "getLPEquity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lpAccumulator",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lpDebt", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "lpEquityDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "totalLP", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalLPEquitySupply",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "CLAIM_FEE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FIXED_NODE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "FOUNDATION", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PARTNER", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "coreContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dqToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLPEquity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lpAccumulator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpDebt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lpEquityDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totalLP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalLPEquitySupply",
    data: BytesLike
  ): Result;
}

export interface IDQMiningStakeCore extends BaseContract {
  connect(runner?: ContractRunner | null): IDQMiningStakeCore;
  waitForDeployment(): Promise<this>;

  interface: IDQMiningStakeCoreInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  CLAIM_FEE: TypedContractMethod<[], [bigint], "view">;

  FIXED_NODE: TypedContractMethod<[], [string], "view">;

  FOUNDATION: TypedContractMethod<[], [string], "view">;

  PARTNER: TypedContractMethod<[], [string], "view">;

  coreContract: TypedContractMethod<[], [string], "view">;

  dqToken: TypedContractMethod<[], [string], "view">;

  getLP: TypedContractMethod<[_u: AddressLike], [bigint], "view">;

  getLPEquity: TypedContractMethod<[_u: AddressLike], [bigint], "view">;

  lpAccumulator: TypedContractMethod<[], [bigint], "view">;

  lpDebt: TypedContractMethod<[_u: AddressLike], [bigint], "view">;

  lpEquityDebt: TypedContractMethod<[_u: AddressLike], [bigint], "view">;

  totalLP: TypedContractMethod<[], [bigint], "view">;

  totalLPEquitySupply: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "CLAIM_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FIXED_NODE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "FOUNDATION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PARTNER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "coreContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dqToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getLP"
  ): TypedContractMethod<[_u: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLPEquity"
  ): TypedContractMethod<[_u: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpAccumulator"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpDebt"
  ): TypedContractMethod<[_u: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpEquityDebt"
  ): TypedContractMethod<[_u: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalLP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalLPEquitySupply"
  ): TypedContractMethod<[], [bigint], "view">;

  filters: {};
}
