/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface MockDQMiningStakeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PARTNER"
      | "addLP"
      | "claimD"
      | "claimFee"
      | "claimLP"
      | "claimNft"
      | "claimPbnb"
      | "claimPdq"
      | "clmS"
      | "dLevels"
      | "distDQFee"
      | "distLP"
      | "distNFT"
      | "distP"
      | "lpD"
      | "lpS"
      | "lpT"
      | "mine"
      | "partner"
      | "registerDLevel"
      | "stake"
      | "unstake"
      | "withdraw"
      | "withdrawLP"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "PARTNER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addLP",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claimD", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "claimFee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimLP",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimNft",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPbnb",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPdq",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "clmS",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dLevels",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distDQFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distLP",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distNFT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "distP", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "lpD", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "lpS", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "lpT", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "mine", values?: undefined): string;
  encodeFunctionData(functionFragment: "partner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDLevel",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawLP",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "PARTNER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addLP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimLP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimNft", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimPbnb", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimPdq", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "clmS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dLevels", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "distDQFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "distLP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "distNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "distP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mine", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "partner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdrawLP", data: BytesLike): Result;
}

export interface MockDQMiningStake extends BaseContract {
  connect(runner?: ContractRunner | null): MockDQMiningStake;
  waitForDeployment(): Promise<this>;

  interface: MockDQMiningStakeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PARTNER: TypedContractMethod<[], [string], "view">;

  addLP: TypedContractMethod<
    [u: AddressLike, a: BigNumberish, t: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimD: TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;

  claimFee: TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;

  claimLP: TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;

  claimNft: TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;

  claimPbnb: TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;

  claimPdq: TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;

  clmS: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;

  dLevels: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  distDQFee: TypedContractMethod<[arg0: BigNumberish], [void], "nonpayable">;

  distLP: TypedContractMethod<[arg0: BigNumberish], [void], "nonpayable">;

  distNFT: TypedContractMethod<[arg0: BigNumberish], [void], "payable">;

  distP: TypedContractMethod<[arg0: BigNumberish], [void], "nonpayable">;

  lpD: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  lpS: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  lpT: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  mine: TypedContractMethod<[], [void], "nonpayable">;

  partner: TypedContractMethod<[], [string], "view">;

  registerDLevel: TypedContractMethod<
    [_user: AddressLike, _level: BigNumberish],
    [void],
    "nonpayable"
  >;

  stake: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawLP: TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PARTNER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addLP"
  ): TypedContractMethod<
    [u: AddressLike, a: BigNumberish, t: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimD"
  ): TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimFee"
  ): TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimLP"
  ): TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimNft"
  ): TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimPbnb"
  ): TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimPdq"
  ): TypedContractMethod<[arg0: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "clmS"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "dLevels"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "distDQFee"
  ): TypedContractMethod<[arg0: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distLP"
  ): TypedContractMethod<[arg0: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distNFT"
  ): TypedContractMethod<[arg0: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "distP"
  ): TypedContractMethod<[arg0: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "lpD"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpS"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpT"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "mine"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "partner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerDLevel"
  ): TypedContractMethod<
    [_user: AddressLike, _level: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawLP"
  ): TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;

  filters: {};
}
