-- DQProject 数据库初始化脚本
-- 在 Supabase SQL Editor 中执行

-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.address_restrictions (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_address character varying NOT NULL UNIQUE,
  reason text,
  restricted_at timestamp with time zone NOT NULL DEFAULT now(),
  unrestricted_at timestamp with time zone,
  restricted_by bigint,
  status character varying NOT NULL DEFAULT 'restricted'::character varying,
  restricted_debt numeric NOT NULL DEFAULT '0'::numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT address_restrictions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admins (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  username character varying NOT NULL UNIQUE,
  password_hash character varying NOT NULL,
  role character varying NOT NULL DEFAULT 'admin'::character varying,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  last_login timestamp with time zone,
  CONSTRAINT admins_pkey PRIMARY KEY (id)
);
CREATE TABLE public.block_rewards (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  release_amount numeric NOT NULL,
  burn_amount numeric NOT NULL,
  burn_rate numeric NOT NULL,
  lp_share numeric NOT NULL,
  nft_share numeric NOT NULL,
  fund_share numeric NOT NULL,
  team_share numeric NOT NULL,
  block_time timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT block_rewards_pkey PRIMARY KEY (id)
);
CREATE TABLE public.cards (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  token_id integer NOT NULL UNIQUE,
  owner_address character varying NOT NULL,
  card_type integer NOT NULL,
  mint_price numeric NOT NULL,
  dq_reward numeric NOT NULL DEFAULT '0'::numeric,
  fee_reward numeric NOT NULL DEFAULT '0'::numeric,
  status character varying NOT NULL DEFAULT 'active'::character varying,
  minted_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT cards_pkey PRIMARY KEY (id)
);
CREATE TABLE public.contract_config (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  config_key character varying NOT NULL UNIQUE,
  config_value text,
  description text,
  updated_at timestamp without time zone DEFAULT now(),
  updated_by character varying,
  CONSTRAINT contract_config_pkey PRIMARY KEY (id)
);

INSERT INTO contract_config (config_key, config_value, description) VALUES
('contract_address', '{"address": "0x1F45f166Dc74C0FAb7a1A5C3Eb1Ff2b0DA68c906"}', '主合约地址'),
('dqtoken_address', '{"address": ""}', 'DQ代币地址'),
('dqcard_address', '{"address": ""}', 'NFT卡牌地址'),
('invest_min', '{"unit": "SOL", "value": "1", "editable": false}', '最小投资金额（固定）'),
('invest_max_start', '{"unit": "SOL", "value": "10", "editable": true}', '初始最大投资金额'),
('invest_max_step', '{"unit": "SOL", "value": "10", "editable": true}', '每阶段最大投资增加量'),
('invest_max_final', '{"unit": "SOL", "value": "200", "editable": true}', '最终最大投资金额'),
('phase_duration', '{"unit": "days", "value": "15", "editable": true}', '每阶段持续天数'),
('level_thresholds', '{"labels": ["S1", "S2", "S3", "S4", "S5", "S6"], "rewards": [5, 10, 15, 20, 25, 30], "thresholds": [100, 200, 600, 2000, 6000, 20000], "editable": false}', '等级晋级门槛'),
('d_level_thresholds', '{"labels": ["D1", "D2", "D3", "D4", "D5", "D6", "D7", "D8"], "thresholds": [30, 120, 360, 1000, 4000, 10000, 15000, 30000], "editable": false}', 'D级门槛'),
('card_config', '{"cards": {"A": {"price": 500, "total": 1000, "remaining": 1000, "unit": "USDT", "reward_weight": 4}, "B": {"price": 1500, "total": 500, "remaining": 500, "unit": "USDT", "reward_weight": 5}, "C": {"price": 5000, "total": 100, "remaining": 100, "unit": "USDT", "reward_weight": 6}}, "requirements": {"A": 5, "B": 10, "C": 20}, "editable": false}', 'NFT卡牌配置'),
('partner_requirements', '{"first_phase": {"direct_sales": 30000, "personal_invest": 5000}, "second_phase": {"direct_sales": 50000, "personal_invest": 5000}, "total_limit": 50, "editable": true}', '合伙人资格要求'),
('stake_config', '{"periods": [30, 90, 180, 360], "rates": [5, 10, 15, 20], "unit": "days", "editable": false}', '质押配置'),
('reward_distribution', '{"deposit_split": {"dynamic": 50, "lp": 50}, "dynamic_split": {"dao": 10, "direct": 30, "insurance": 7, "management": 30, "node": 15, "operation": 8}, "editable": false}', '奖励分配比例'),
('withdraw_fee', '{"rate": 10, "split": {"foundation": 30, "nft": 40, "partner": 30}, "editable": false}', '提现手续费'),
('lp_remove_fee', '{"rules": [{"days": "<60", "rate": 20}, {"days": "60-180", "rate": 10}, {"days": ">180", "rate": 0}], "editable": false}', 'LP赎回手续费规则');

CREATE TABLE public.deposits (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tx_hash character varying NOT NULL UNIQUE,
  user_address character varying NOT NULL,
  amount numeric NOT NULL,
  phase integer NOT NULL,
  status character varying NOT NULL DEFAULT 'completed'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT deposits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lp_stakes (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_address character varying NOT NULL,
  amount numeric NOT NULL,
  stake_days integer NOT NULL,
  start_time timestamp with time zone NOT NULL DEFAULT now(),
  end_time timestamp with time zone,
  reward_amount numeric NOT NULL DEFAULT '0'::numeric,
  is_claimed boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT lp_stakes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.node_applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_address character varying NOT NULL,
  user_name character varying,
  apply_type character varying NOT NULL,
  apply_reason text,
  contact_info character varying,
  total_invest numeric NOT NULL DEFAULT '0'::numeric,
  team_size integer NOT NULL DEFAULT 0,
  attachment_url text,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  reviewer_id bigint,
  reviewer_notes text,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT node_applications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.operation_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  admin_id bigint,
  admin_address character varying,
  action character varying NOT NULL,
  target character varying,
  details text,
  ip_address character varying,
  created_at timestamp without time zone DEFAULT now(),
  CONSTRAINT operation_logs_pkey PRIMARY KEY (id),
  CONSTRAINT operation_logs_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admins(id)
);
CREATE TABLE public.partners (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_address character varying NOT NULL UNIQUE,
  "order" integer NOT NULL,
  personal_invest numeric NOT NULL,
  direct_sales numeric NOT NULL,
  dq_reward numeric NOT NULL DEFAULT '0'::numeric,
  sol_reward numeric NOT NULL DEFAULT '0'::numeric,
  status character varying NOT NULL DEFAULT 'active'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT partners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pools (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  pool_name character varying NOT NULL UNIQUE,
  balance numeric NOT NULL DEFAULT '0'::numeric,
  total_distributed numeric NOT NULL DEFAULT '0'::numeric,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT pools_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rewards (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_address character varying NOT NULL,
  reward_type character varying NOT NULL,
  amount numeric NOT NULL,
  from_address character varying,
  level integer,
  tx_hash character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT rewards_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sol_rewards (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  user_address character varying NOT NULL,
  amount numeric NOT NULL,
  lp_amount numeric NOT NULL,
  tx_hash character varying NOT NULL,
  block_number bigint,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sol_rewards_pkey PRIMARY KEY (id)
);

CREATE TABLE public.users (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  wallet_address character varying NOT NULL UNIQUE,
  referrer_address character varying,
  direct_count integer NOT NULL DEFAULT 0,
  level integer NOT NULL DEFAULT 0,
  total_invest numeric NOT NULL DEFAULT '0'::numeric,
  team_invest numeric NOT NULL DEFAULT '0'::numeric,
  energy numeric NOT NULL DEFAULT '0'::numeric,
  lp_shares numeric NOT NULL DEFAULT '0'::numeric,
  pending_rewards numeric NOT NULL DEFAULT '0'::numeric,
  direct_sales numeric NOT NULL DEFAULT '0'::numeric,
  d_level integer NOT NULL DEFAULT 0,
  qualified_lines integer NOT NULL DEFAULT 0,
  is_node_qualified boolean NOT NULL DEFAULT false,
  highest_card_type integer NOT NULL DEFAULT 0,
  is_partner boolean NOT NULL DEFAULT false,
  partner_order integer,
  card_type integer,
  nft_token_id integer,
  is_restricted boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone,
  is_activated boolean DEFAULT false,
  activation_tx_hash character varying,
  activated_at timestamp with time zone,
  valid_address_count integer NOT NULL DEFAULT 0,
  CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE public.team_closure (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  ancestor_id bigint NOT NULL,
  descendant_id bigint NOT NULL,
  depth integer NOT NULL DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT team_closure_pkey PRIMARY KEY (id),
  CONSTRAINT team_closure_ancestor_id_fkey FOREIGN KEY (ancestor_id) REFERENCES public.users(id),
  CONSTRAINT team_closure_descendant_id_fkey FOREIGN KEY (descendant_id) REFERENCES public.users(id)
);

CREATE TABLE public.withdrawals (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  tx_hash character varying NOT NULL UNIQUE,
  user_address character varying NOT NULL,
  amount numeric NOT NULL,
  fee numeric NOT NULL,
  withdraw_type character varying NOT NULL,
  stake_days integer,
  status character varying NOT NULL DEFAULT 'pending'::character varying,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT withdrawals_pkey PRIMARY KEY (id)
);

-- 创建每个表缺失的索引，主要针对查询频繁的字段
CREATE INDEX idx_users_referrer_address ON public.users (referrer_address);
CREATE INDEX idx_users_level ON public.users (level);
CREATE INDEX idx_users_d_level ON public.users (d_level);
CREATE INDEX idx_users_is_partner ON public.users (is_partner);
CREATE INDEX idx_deposits_user_address ON public.deposits (user_address);
CREATE INDEX idx_deposits_status ON public.deposits (status);
CREATE INDEX idx_lp_stakes_user_address ON public.lp_stakes (user_address);
CREATE INDEX idx_node_applications_user_address ON public.node_applications (user_address);
CREATE INDEX idx_node_applications_status ON public.node_applications (status);
CREATE INDEX idx_partners_user_address ON public.partners (user_address);
CREATE INDEX idx_rewards_user_address ON public.rewards (user_address);
CREATE INDEX idx_rewards_reward_type ON public.rewards (reward_type);
CREATE INDEX idx_sol_rewards_user_address ON public.sol_rewards (user_address);
CREATE INDEX idx_sol_rewards_block_number ON public.sol_rewards (block_number);
CREATE INDEX idx_withdrawals_user_address ON public.withdrawals (user_address);
CREATE INDEX idx_withdrawals_status ON public.withdrawals (status);

-- 创建触发器函数和触发器
-- RPC: 获取待重建团队闭包关系的用户
CREATE OR REPLACE FUNCTION get_pending_team_closure_users(
    p_limit integer DEFAULT 100,
    p_offset integer DEFAULT 0
)
RETURNS TABLE (
  id bigint,
    wallet_address varchar,
    referrer_address varchar,
    total_pending bigint
)
LANGUAGE sql
STABLE
AS $$
WITH pending AS (
    SELECT
        u.id,
        u.wallet_address,
        u.referrer_address
    FROM users u
    WHERE u.referrer_address IS NOT NULL
      AND u.referrer_address <> ''
      AND u.referrer_address <> '0x0000000000000000000000000000000000000000'
      AND NOT EXISTS (
          SELECT 1
          FROM team_closure tc
          WHERE tc.descendant_id = u.id
      )
    ORDER BY u.id
)
SELECT
    id,
    wallet_address,
    referrer_address,
    COUNT(*) OVER() AS total_pending
FROM pending
OFFSET GREATEST(p_offset, 0)
LIMIT GREATEST(p_limit, 0);
$$;

-- 初始化默认管理员 (密码: admin123)
INSERT INTO admins (username, password_hash, role) 
VALUES ('admin', '$2b$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2.uheWG/igi', 'super_admin')
ON CONFLICT (username) DO NOTHING;

-- 初始化资金池
INSERT INTO pools (pool_name, balance) VALUES
    ('management', '0'), ('dao', '0'), ('insurance', '0'),
    ('operation', '0'), ('fee', '0'), ('lp', '0')
ON CONFLICT (pool_name) DO NOTHING;

SELECT 'Database initialized successfully!' AS status;
