/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DQMiningV4Interface extends Interface {
  getFunction(
    nameOrSignature:
      | "BURN_STOP_THRESHOLD"
      | "BUY_FEE"
      | "DAILY_LIMIT"
      | "DAO"
      | "DAO_RATE"
      | "DIRECT_RATE"
      | "ENERGY_MUL"
      | "FEE_FOUNDATION_RATE"
      | "FEE_NODE_RATE"
      | "FEE_PARTNER_RATE"
      | "FOUNDATION"
      | "INITIAL_SUPPLY"
      | "INS"
      | "INS_RATE"
      | "INVEST_MIN"
      | "MGR_RATE"
      | "OP"
      | "OP_RATE"
      | "OWNER"
      | "PARTNER"
      | "PHASE_STEP"
      | "ROUTER"
      | "SEE_RATE"
      | "SELL_FEE"
      | "SLIPPAGE"
      | "SOL"
      | "STAKE_OP"
      | "WITHDRAW_FEE"
      | "addToBlacklist"
      | "adminWithdrawAnyToken"
      | "adminWithdrawDQ"
      | "adminWithdrawLP"
      | "adminWithdrawSOL"
      | "advancePhase"
      | "allUsers"
      | "approveRouter"
      | "authorized"
      | "buyNode"
      | "claimDTeam"
      | "claimFee"
      | "claimLP"
      | "claimNft"
      | "claimReward"
      | "claimStakeReward"
      | "createLPFromBalance"
      | "currentPhase"
      | "dailyDeposit"
      | "depositForUser"
      | "depositSOL"
      | "depositWhiteList"
      | "distributeFeeToNFT"
      | "dqCard"
      | "dqToken"
      | "feeAddr"
      | "getAllUsersLength"
      | "getDailyLimit"
      | "getPendingSOL"
      | "getTeamSize"
      | "getUser"
      | "getUserStake"
      | "importNodes"
      | "importUser"
      | "importUsers"
      | "isBlacklisted"
      | "manualAddLP"
      | "mineBlock"
      | "nftPendingSOL"
      | "nodePrices"
      | "receiveBurn"
      | "register"
      | "removeFromBlacklist"
      | "sellDQForSOL"
      | "setDQCard"
      | "setDQToken"
      | "setFeeAddr"
      | "setFoundation"
      | "setNodesDLevel"
      | "setNodesLevel"
      | "setReferrer"
      | "setSlippage"
      | "setStakeContract"
      | "stakeContract"
      | "stakeDQ"
      | "startTime"
      | "unstakeDQ"
      | "withdraw"
      | "withdrawBNB"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "BurnFromDQT"
      | "ClaimReward"
      | "Deposit"
      | "Register"
      | "ReinvestSOL"
      | "SellDQ"
      | "SwapAndAddLP"
      | "WithdrawBNB"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BURN_STOP_THRESHOLD",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BUY_FEE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DAILY_LIMIT",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "DAO", values?: undefined): string;
  encodeFunctionData(functionFragment: "DAO_RATE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "DIRECT_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "ENERGY_MUL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_FOUNDATION_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_NODE_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FEE_PARTNER_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "FOUNDATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INITIAL_SUPPLY",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "INS", values?: undefined): string;
  encodeFunctionData(functionFragment: "INS_RATE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "INVEST_MIN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "MGR_RATE", values?: undefined): string;
  encodeFunctionData(functionFragment: "OP", values?: undefined): string;
  encodeFunctionData(functionFragment: "OP_RATE", values?: undefined): string;
  encodeFunctionData(functionFragment: "OWNER", values?: undefined): string;
  encodeFunctionData(functionFragment: "PARTNER", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "PHASE_STEP",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "ROUTER", values?: undefined): string;
  encodeFunctionData(functionFragment: "SEE_RATE", values?: undefined): string;
  encodeFunctionData(functionFragment: "SELL_FEE", values?: undefined): string;
  encodeFunctionData(functionFragment: "SLIPPAGE", values?: undefined): string;
  encodeFunctionData(functionFragment: "SOL", values?: undefined): string;
  encodeFunctionData(functionFragment: "STAKE_OP", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "WITHDRAW_FEE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addToBlacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdrawAnyToken",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdrawDQ",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdrawLP",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdrawSOL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "advancePhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allUsers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "approveRouter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "authorized",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "buyNode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDTeam",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claimFee", values?: undefined): string;
  encodeFunctionData(functionFragment: "claimLP", values?: undefined): string;
  encodeFunctionData(functionFragment: "claimNft", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimReward",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimStakeReward",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createLPFromBalance",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "currentPhase",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dailyDeposit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositForUser",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositSOL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositWhiteList",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeFeeToNFT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "dqCard", values?: undefined): string;
  encodeFunctionData(functionFragment: "dqToken", values?: undefined): string;
  encodeFunctionData(functionFragment: "feeAddr", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getAllUsersLength",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getDailyLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingSOL",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTeamSize",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "importNodes",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "importUser",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "importUsers",
    values: [AddressLike[], AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "isBlacklisted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manualAddLP",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "mineBlock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nftPendingSOL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nodePrices",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveBurn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromBlacklist",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sellDQForSOL",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setDQCard",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDQToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFeeAddr",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFoundation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setNodesDLevel",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setNodesLevel",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setReferrer",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSlippage",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setStakeContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "stakeDQ",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "startTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "unstakeDQ",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBNB",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BURN_STOP_THRESHOLD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BUY_FEE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DAILY_LIMIT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "DAO", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "DAO_RATE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DIRECT_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ENERGY_MUL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "FEE_FOUNDATION_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_NODE_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "FEE_PARTNER_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "FOUNDATION", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "INITIAL_SUPPLY",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "INS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "INS_RATE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "INVEST_MIN", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "MGR_RATE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "OP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "OP_RATE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "OWNER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PARTNER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "PHASE_STEP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ROUTER", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SEE_RATE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SELL_FEE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SLIPPAGE", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "SOL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "STAKE_OP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "WITHDRAW_FEE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addToBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdrawAnyToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdrawDQ",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdrawLP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdrawSOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "advancePhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "approveRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "authorized", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyNode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimDTeam", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimLP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimStakeReward",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createLPFromBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "currentPhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyDeposit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositForUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "depositSOL", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositWhiteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributeFeeToNFT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "dqCard", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dqToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeAddr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllUsersLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDailyLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingSOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTeamSize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "importNodes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "importUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "importUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isBlacklisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manualAddLP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mineBlock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nftPendingSOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nodePrices", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "receiveBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeFromBlacklist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellDQForSOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setDQCard", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setDQToken", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setFeeAddr", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setFoundation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNodesDLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setNodesLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReferrer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSlippage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setStakeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakeDQ", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "startTime", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unstakeDQ", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBNB",
    data: BytesLike
  ): Result;
}

export namespace BurnFromDQTEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimRewardEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    fee: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, fee: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    fee: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [u: AddressLike, a: BigNumberish];
  export type OutputTuple = [u: string, a: bigint];
  export interface OutputObject {
    u: string;
    a: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegisterEvent {
  export type InputTuple = [u: AddressLike, r: AddressLike];
  export type OutputTuple = [u: string, r: string];
  export interface OutputObject {
    u: string;
    r: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReinvestSOLEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    energyAdded: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, energyAdded: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    energyAdded: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SellDQEvent {
  export type InputTuple = [
    u: AddressLike,
    d: BigNumberish,
    s: BigNumberish,
    b: BigNumberish,
    f: BigNumberish
  ];
  export type OutputTuple = [
    u: string,
    d: bigint,
    s: bigint,
    b: bigint,
    f: bigint
  ];
  export interface OutputObject {
    u: string;
    d: bigint;
    s: bigint;
    b: bigint;
    f: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwapAndAddLPEvent {
  export type InputTuple = [
    u: AddressLike,
    s: BigNumberish,
    d: BigNumberish,
    l: BigNumberish
  ];
  export type OutputTuple = [u: string, s: bigint, d: bigint, l: bigint];
  export interface OutputObject {
    u: string;
    s: bigint;
    d: bigint;
    l: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawBNBEvent {
  export type InputTuple = [to: AddressLike, amount: BigNumberish];
  export type OutputTuple = [to: string, amount: bigint];
  export interface OutputObject {
    to: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DQMiningV4 extends BaseContract {
  connect(runner?: ContractRunner | null): DQMiningV4;
  waitForDeployment(): Promise<this>;

  interface: DQMiningV4Interface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BURN_STOP_THRESHOLD: TypedContractMethod<[], [bigint], "view">;

  BUY_FEE: TypedContractMethod<[], [string], "view">;

  DAILY_LIMIT: TypedContractMethod<[], [bigint], "view">;

  DAO: TypedContractMethod<[], [string], "view">;

  DAO_RATE: TypedContractMethod<[], [bigint], "view">;

  DIRECT_RATE: TypedContractMethod<[], [bigint], "view">;

  ENERGY_MUL: TypedContractMethod<[], [bigint], "view">;

  FEE_FOUNDATION_RATE: TypedContractMethod<[], [bigint], "view">;

  FEE_NODE_RATE: TypedContractMethod<[], [bigint], "view">;

  FEE_PARTNER_RATE: TypedContractMethod<[], [bigint], "view">;

  FOUNDATION: TypedContractMethod<[], [string], "view">;

  INITIAL_SUPPLY: TypedContractMethod<[], [bigint], "view">;

  INS: TypedContractMethod<[], [string], "view">;

  INS_RATE: TypedContractMethod<[], [bigint], "view">;

  INVEST_MIN: TypedContractMethod<[], [bigint], "view">;

  MGR_RATE: TypedContractMethod<[], [bigint], "view">;

  OP: TypedContractMethod<[], [string], "view">;

  OP_RATE: TypedContractMethod<[], [bigint], "view">;

  OWNER: TypedContractMethod<[], [string], "view">;

  PARTNER: TypedContractMethod<[], [string], "view">;

  PHASE_STEP: TypedContractMethod<[], [bigint], "view">;

  ROUTER: TypedContractMethod<[], [string], "view">;

  SEE_RATE: TypedContractMethod<[], [bigint], "view">;

  SELL_FEE: TypedContractMethod<[], [bigint], "view">;

  SLIPPAGE: TypedContractMethod<[], [bigint], "view">;

  SOL: TypedContractMethod<[], [string], "view">;

  STAKE_OP: TypedContractMethod<[], [string], "view">;

  WITHDRAW_FEE: TypedContractMethod<[], [bigint], "view">;

  addToBlacklist: TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;

  adminWithdrawAnyToken: TypedContractMethod<
    [_token: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  adminWithdrawDQ: TypedContractMethod<
    [_a: BigNumberish],
    [void],
    "nonpayable"
  >;

  adminWithdrawLP: TypedContractMethod<
    [_lpToken: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  adminWithdrawSOL: TypedContractMethod<
    [_a: BigNumberish],
    [void],
    "nonpayable"
  >;

  advancePhase: TypedContractMethod<[], [void], "nonpayable">;

  allUsers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  approveRouter: TypedContractMethod<[], [void], "nonpayable">;

  authorized: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  buyNode: TypedContractMethod<[_t: BigNumberish], [void], "nonpayable">;

  claimDTeam: TypedContractMethod<[], [void], "nonpayable">;

  claimFee: TypedContractMethod<[], [void], "nonpayable">;

  claimLP: TypedContractMethod<[], [void], "nonpayable">;

  claimNft: TypedContractMethod<[], [void], "nonpayable">;

  claimReward: TypedContractMethod<[], [void], "nonpayable">;

  claimStakeReward: TypedContractMethod<
    [_periodIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  createLPFromBalance: TypedContractMethod<
    [_user: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  currentPhase: TypedContractMethod<[], [bigint], "view">;

  dailyDeposit: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  depositForUser: TypedContractMethod<
    [_user: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositSOL: TypedContractMethod<[_a: BigNumberish], [void], "nonpayable">;

  depositWhiteList: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  distributeFeeToNFT: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  dqCard: TypedContractMethod<[], [string], "view">;

  dqToken: TypedContractMethod<[], [string], "view">;

  feeAddr: TypedContractMethod<[], [string], "view">;

  getAllUsersLength: TypedContractMethod<[], [bigint], "view">;

  getDailyLimit: TypedContractMethod<[], [bigint], "view">;

  getPendingSOL: TypedContractMethod<[_u: AddressLike], [bigint], "view">;

  getTeamSize: TypedContractMethod<[_u: AddressLike], [bigint], "view">;

  getUser: TypedContractMethod<
    [_u: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        referrer: string;
        directCount: bigint;
        level: bigint;
        totalInvest: bigint;
      }
    ],
    "view"
  >;

  getUserStake: TypedContractMethod<
    [_u: AddressLike],
    [
      [bigint, bigint, bigint] & {
        teamInvest: bigint;
        energy: bigint;
        pendingSOL: bigint;
      }
    ],
    "view"
  >;

  importNodes: TypedContractMethod<
    [_u: AddressLike[], _t: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  importUser: TypedContractMethod<
    [_u: AddressLike, _r: AddressLike],
    [void],
    "nonpayable"
  >;

  importUsers: TypedContractMethod<
    [_u: AddressLike[], _r: AddressLike[]],
    [void],
    "nonpayable"
  >;

  isBlacklisted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  manualAddLP: TypedContractMethod<
    [_user: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  mineBlock: TypedContractMethod<[], [void], "nonpayable">;

  nftPendingSOL: TypedContractMethod<[], [bigint], "view">;

  nodePrices: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  receiveBurn: TypedContractMethod<
    [_amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  register: TypedContractMethod<[_r: AddressLike], [void], "nonpayable">;

  removeFromBlacklist: TypedContractMethod<
    [_u: AddressLike],
    [void],
    "nonpayable"
  >;

  sellDQForSOL: TypedContractMethod<
    [_dq: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  setDQCard: TypedContractMethod<[_addr: AddressLike], [void], "nonpayable">;

  setDQToken: TypedContractMethod<[_addr: AddressLike], [void], "nonpayable">;

  setFeeAddr: TypedContractMethod<[_addr: AddressLike], [void], "nonpayable">;

  setFoundation: TypedContractMethod<
    [_addr: AddressLike],
    [void],
    "nonpayable"
  >;

  setNodesDLevel: TypedContractMethod<
    [_u: AddressLike[], _lvl: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  setNodesLevel: TypedContractMethod<
    [_u: AddressLike[], _lvl: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  setReferrer: TypedContractMethod<
    [_u: AddressLike, _r: AddressLike],
    [void],
    "nonpayable"
  >;

  setSlippage: TypedContractMethod<[_s: BigNumberish], [void], "nonpayable">;

  setStakeContract: TypedContractMethod<
    [_a: AddressLike],
    [void],
    "nonpayable"
  >;

  stakeContract: TypedContractMethod<[], [string], "view">;

  stakeDQ: TypedContractMethod<
    [_amount: BigNumberish, _periodIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  startTime: TypedContractMethod<[], [bigint], "view">;

  unstakeDQ: TypedContractMethod<
    [_periodIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[_a: BigNumberish], [void], "nonpayable">;

  withdrawBNB: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BURN_STOP_THRESHOLD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "BUY_FEE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DAILY_LIMIT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DAO"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DAO_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "DIRECT_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ENERGY_MUL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_FOUNDATION_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_NODE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FEE_PARTNER_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "FOUNDATION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INITIAL_SUPPLY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INS"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "INS_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INVEST_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MGR_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(nameOrSignature: "OP"): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "OP_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "OWNER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PARTNER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "PHASE_STEP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "ROUTER"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "SEE_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SELL_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SLIPPAGE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "SOL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "STAKE_OP"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "WITHDRAW_FEE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addToBlacklist"
  ): TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminWithdrawAnyToken"
  ): TypedContractMethod<
    [_token: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "adminWithdrawDQ"
  ): TypedContractMethod<[_a: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminWithdrawLP"
  ): TypedContractMethod<
    [_lpToken: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "adminWithdrawSOL"
  ): TypedContractMethod<[_a: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "advancePhase"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allUsers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "approveRouter"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorized"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "buyNode"
  ): TypedContractMethod<[_t: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimDTeam"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimFee"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimLP"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimNft"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimReward"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimStakeReward"
  ): TypedContractMethod<[_periodIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createLPFromBalance"
  ): TypedContractMethod<
    [_user: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "currentPhase"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyDeposit"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositForUser"
  ): TypedContractMethod<
    [_user: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositSOL"
  ): TypedContractMethod<[_a: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositWhiteList"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "distributeFeeToNFT"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dqCard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dqToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeAddr"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getAllUsersLength"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDailyLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingSOL"
  ): TypedContractMethod<[_u: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTeamSize"
  ): TypedContractMethod<[_u: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [_u: AddressLike],
    [
      [string, bigint, bigint, bigint] & {
        referrer: string;
        directCount: bigint;
        level: bigint;
        totalInvest: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserStake"
  ): TypedContractMethod<
    [_u: AddressLike],
    [
      [bigint, bigint, bigint] & {
        teamInvest: bigint;
        energy: bigint;
        pendingSOL: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "importNodes"
  ): TypedContractMethod<
    [_u: AddressLike[], _t: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "importUser"
  ): TypedContractMethod<
    [_u: AddressLike, _r: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "importUsers"
  ): TypedContractMethod<
    [_u: AddressLike[], _r: AddressLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isBlacklisted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "manualAddLP"
  ): TypedContractMethod<
    [_user: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mineBlock"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "nftPendingSOL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nodePrices"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "receiveBurn"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[_r: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeFromBlacklist"
  ): TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sellDQForSOL"
  ): TypedContractMethod<[_dq: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "setDQCard"
  ): TypedContractMethod<[_addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDQToken"
  ): TypedContractMethod<[_addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFeeAddr"
  ): TypedContractMethod<[_addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setFoundation"
  ): TypedContractMethod<[_addr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setNodesDLevel"
  ): TypedContractMethod<
    [_u: AddressLike[], _lvl: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setNodesLevel"
  ): TypedContractMethod<
    [_u: AddressLike[], _lvl: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setReferrer"
  ): TypedContractMethod<
    [_u: AddressLike, _r: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setSlippage"
  ): TypedContractMethod<[_s: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStakeContract"
  ): TypedContractMethod<[_a: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakeContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "stakeDQ"
  ): TypedContractMethod<
    [_amount: BigNumberish, _periodIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "unstakeDQ"
  ): TypedContractMethod<[_periodIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[_a: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawBNB"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "BurnFromDQT"
  ): TypedContractEvent<
    BurnFromDQTEvent.InputTuple,
    BurnFromDQTEvent.OutputTuple,
    BurnFromDQTEvent.OutputObject
  >;
  getEvent(
    key: "ClaimReward"
  ): TypedContractEvent<
    ClaimRewardEvent.InputTuple,
    ClaimRewardEvent.OutputTuple,
    ClaimRewardEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "Register"
  ): TypedContractEvent<
    RegisterEvent.InputTuple,
    RegisterEvent.OutputTuple,
    RegisterEvent.OutputObject
  >;
  getEvent(
    key: "ReinvestSOL"
  ): TypedContractEvent<
    ReinvestSOLEvent.InputTuple,
    ReinvestSOLEvent.OutputTuple,
    ReinvestSOLEvent.OutputObject
  >;
  getEvent(
    key: "SellDQ"
  ): TypedContractEvent<
    SellDQEvent.InputTuple,
    SellDQEvent.OutputTuple,
    SellDQEvent.OutputObject
  >;
  getEvent(
    key: "SwapAndAddLP"
  ): TypedContractEvent<
    SwapAndAddLPEvent.InputTuple,
    SwapAndAddLPEvent.OutputTuple,
    SwapAndAddLPEvent.OutputObject
  >;
  getEvent(
    key: "WithdrawBNB"
  ): TypedContractEvent<
    WithdrawBNBEvent.InputTuple,
    WithdrawBNBEvent.OutputTuple,
    WithdrawBNBEvent.OutputObject
  >;

  filters: {
    "BurnFromDQT(address,uint256)": TypedContractEvent<
      BurnFromDQTEvent.InputTuple,
      BurnFromDQTEvent.OutputTuple,
      BurnFromDQTEvent.OutputObject
    >;
    BurnFromDQT: TypedContractEvent<
      BurnFromDQTEvent.InputTuple,
      BurnFromDQTEvent.OutputTuple,
      BurnFromDQTEvent.OutputObject
    >;

    "ClaimReward(address,uint256,uint256)": TypedContractEvent<
      ClaimRewardEvent.InputTuple,
      ClaimRewardEvent.OutputTuple,
      ClaimRewardEvent.OutputObject
    >;
    ClaimReward: TypedContractEvent<
      ClaimRewardEvent.InputTuple,
      ClaimRewardEvent.OutputTuple,
      ClaimRewardEvent.OutputObject
    >;

    "Deposit(address,uint256)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "Register(address,address)": TypedContractEvent<
      RegisterEvent.InputTuple,
      RegisterEvent.OutputTuple,
      RegisterEvent.OutputObject
    >;
    Register: TypedContractEvent<
      RegisterEvent.InputTuple,
      RegisterEvent.OutputTuple,
      RegisterEvent.OutputObject
    >;

    "ReinvestSOL(address,uint256,uint256)": TypedContractEvent<
      ReinvestSOLEvent.InputTuple,
      ReinvestSOLEvent.OutputTuple,
      ReinvestSOLEvent.OutputObject
    >;
    ReinvestSOL: TypedContractEvent<
      ReinvestSOLEvent.InputTuple,
      ReinvestSOLEvent.OutputTuple,
      ReinvestSOLEvent.OutputObject
    >;

    "SellDQ(address,uint256,uint256,uint256,uint256)": TypedContractEvent<
      SellDQEvent.InputTuple,
      SellDQEvent.OutputTuple,
      SellDQEvent.OutputObject
    >;
    SellDQ: TypedContractEvent<
      SellDQEvent.InputTuple,
      SellDQEvent.OutputTuple,
      SellDQEvent.OutputObject
    >;

    "SwapAndAddLP(address,uint256,uint256,uint256)": TypedContractEvent<
      SwapAndAddLPEvent.InputTuple,
      SwapAndAddLPEvent.OutputTuple,
      SwapAndAddLPEvent.OutputObject
    >;
    SwapAndAddLP: TypedContractEvent<
      SwapAndAddLPEvent.InputTuple,
      SwapAndAddLPEvent.OutputTuple,
      SwapAndAddLPEvent.OutputObject
    >;

    "WithdrawBNB(address,uint256)": TypedContractEvent<
      WithdrawBNBEvent.InputTuple,
      WithdrawBNBEvent.OutputTuple,
      WithdrawBNBEvent.OutputObject
    >;
    WithdrawBNB: TypedContractEvent<
      WithdrawBNBEvent.InputTuple,
      WithdrawBNBEvent.OutputTuple,
      WithdrawBNBEvent.OutputObject
    >;
  };
}
