/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IDQMiningStakeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addChild"
      | "addDirectSales"
      | "addEnergy"
      | "addLP"
      | "addPendingBurn"
      | "addPendingSOL"
      | "addTeamInvest"
      | "claimD"
      | "claimFee"
      | "claimLP"
      | "claimNft"
      | "claimPbnb"
      | "claimPdq"
      | "clearUserLPRemovalFee"
      | "clmS"
      | "distDQFee"
      | "distLP"
      | "distNFT"
      | "distReward"
      | "getDirectSales"
      | "getEnergy"
      | "getPendingSOL"
      | "getTeamInvest"
      | "getUserLPRemovalFee"
      | "importUser"
      | "lpPair"
      | "mine"
      | "registerDLevel"
      | "registerUser"
      | "setEnergyMul"
      | "stake"
      | "subEnergy"
      | "subPendingBurn"
      | "subPendingSOL"
      | "unstake"
      | "updateTeam"
      | "updateValidAddress"
      | "withdraw"
      | "withdrawLP"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addChild",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addDirectSales",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addEnergy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addLP",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addPendingBurn",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addPendingSOL",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addTeamInvest",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "claimD", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "claimFee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimLP",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimNft",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPbnb",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimPdq",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "clearUserLPRemovalFee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "clmS",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distDQFee",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distLP",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distNFT",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distReward",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDirectSales",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getEnergy",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingSOL",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getTeamInvest",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserLPRemovalFee",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "importUser",
    values: [
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "lpPair", values?: undefined): string;
  encodeFunctionData(functionFragment: "mine", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerDLevel",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerUser",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setEnergyMul",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stake",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subEnergy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subPendingBurn",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "subPendingSOL",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unstake",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateTeam",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateValidAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawLP",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addChild", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addDirectSales",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addEnergy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "addLP", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addPendingBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPendingSOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addTeamInvest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimD", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimLP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimNft", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimPbnb", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimPdq", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "clearUserLPRemovalFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "clmS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "distDQFee", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "distLP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "distNFT", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "distReward", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDirectSales",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getEnergy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPendingSOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTeamInvest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUserLPRemovalFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "importUser", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpPair", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mine", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerDLevel",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerUser",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEnergyMul",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "subEnergy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subPendingBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "subPendingSOL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unstake", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateTeam", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateValidAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdrawLP", data: BytesLike): Result;
}

export interface IDQMiningStake extends BaseContract {
  connect(runner?: ContractRunner | null): IDQMiningStake;
  waitForDeployment(): Promise<this>;

  interface: IDQMiningStakeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addChild: TypedContractMethod<
    [_p: AddressLike, _c: AddressLike],
    [void],
    "nonpayable"
  >;

  addDirectSales: TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  addEnergy: TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  addLP: TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish, _t: BigNumberish],
    [void],
    "nonpayable"
  >;

  addPendingBurn: TypedContractMethod<[_a: BigNumberish], [void], "nonpayable">;

  addPendingSOL: TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  addTeamInvest: TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimD: TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;

  claimFee: TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;

  claimLP: TypedContractMethod<[u: AddressLike], [void], "nonpayable">;

  claimNft: TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;

  claimPbnb: TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;

  claimPdq: TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;

  clearUserLPRemovalFee: TypedContractMethod<
    [_u: AddressLike],
    [void],
    "nonpayable"
  >;

  clmS: TypedContractMethod<
    [_u: AddressLike, _i: BigNumberish],
    [void],
    "nonpayable"
  >;

  distDQFee: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  distLP: TypedContractMethod<[f: BigNumberish], [void], "nonpayable">;

  distNFT: TypedContractMethod<[_fee: BigNumberish], [void], "payable">;

  distReward: TypedContractMethod<
    [_u: AddressLike, _dyn: BigNumberish],
    [void],
    "nonpayable"
  >;

  getDirectSales: TypedContractMethod<[_u: AddressLike], [bigint], "view">;

  getEnergy: TypedContractMethod<[_u: AddressLike], [bigint], "view">;

  getPendingSOL: TypedContractMethod<[_u: AddressLike], [bigint], "view">;

  getTeamInvest: TypedContractMethod<[_u: AddressLike], [bigint], "view">;

  getUserLPRemovalFee: TypedContractMethod<[_u: AddressLike], [bigint], "view">;

  importUser: TypedContractMethod<
    [
      _u: AddressLike,
      _r: AddressLike,
      _total: BigNumberish,
      _team: BigNumberish,
      _level: BigNumberish,
      _energy: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  lpPair: TypedContractMethod<[], [string], "view">;

  mine: TypedContractMethod<[], [void], "nonpayable">;

  registerDLevel: TypedContractMethod<
    [_user: AddressLike, _level: BigNumberish],
    [void],
    "nonpayable"
  >;

  registerUser: TypedContractMethod<
    [_u: AddressLike, _r: AddressLike],
    [void],
    "nonpayable"
  >;

  setEnergyMul: TypedContractMethod<[_m: BigNumberish], [void], "nonpayable">;

  stake: TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish, _i: BigNumberish],
    [void],
    "nonpayable"
  >;

  subEnergy: TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  subPendingBurn: TypedContractMethod<
    [_u: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  subPendingSOL: TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  unstake: TypedContractMethod<
    [_u: AddressLike, _i: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateTeam: TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateValidAddress: TypedContractMethod<
    [_u: AddressLike],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawLP: TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addChild"
  ): TypedContractMethod<
    [_p: AddressLike, _c: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addDirectSales"
  ): TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addEnergy"
  ): TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addLP"
  ): TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish, _t: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addPendingBurn"
  ): TypedContractMethod<[_a: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addPendingSOL"
  ): TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "addTeamInvest"
  ): TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimD"
  ): TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimFee"
  ): TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimLP"
  ): TypedContractMethod<[u: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimNft"
  ): TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimPbnb"
  ): TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimPdq"
  ): TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "clearUserLPRemovalFee"
  ): TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "clmS"
  ): TypedContractMethod<
    [_u: AddressLike, _i: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distDQFee"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distLP"
  ): TypedContractMethod<[f: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distNFT"
  ): TypedContractMethod<[_fee: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "distReward"
  ): TypedContractMethod<
    [_u: AddressLike, _dyn: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDirectSales"
  ): TypedContractMethod<[_u: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getEnergy"
  ): TypedContractMethod<[_u: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingSOL"
  ): TypedContractMethod<[_u: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTeamInvest"
  ): TypedContractMethod<[_u: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getUserLPRemovalFee"
  ): TypedContractMethod<[_u: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "importUser"
  ): TypedContractMethod<
    [
      _u: AddressLike,
      _r: AddressLike,
      _total: BigNumberish,
      _team: BigNumberish,
      _level: BigNumberish,
      _energy: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lpPair"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "mine"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerDLevel"
  ): TypedContractMethod<
    [_user: AddressLike, _level: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "registerUser"
  ): TypedContractMethod<
    [_u: AddressLike, _r: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setEnergyMul"
  ): TypedContractMethod<[_m: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stake"
  ): TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish, _i: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subEnergy"
  ): TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subPendingBurn"
  ): TypedContractMethod<
    [_u: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "subPendingSOL"
  ): TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unstake"
  ): TypedContractMethod<
    [_u: AddressLike, _i: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateTeam"
  ): TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateValidAddress"
  ): TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<
    [_u: AddressLike, _a: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawLP"
  ): TypedContractMethod<[_u: AddressLike], [void], "nonpayable">;

  filters: {};
}
