/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface DQProjectInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "BEP20_TOKEN"
      | "BLACKHOLE"
      | "BURN_DECREMENT"
      | "INVEST_MAX_FINAL"
      | "INVEST_MAX_START"
      | "INVEST_MAX_STEP"
      | "INVEST_MIN"
      | "MIN_BURN_RATE"
      | "PHASE_DURATION"
      | "addPartnerWhiteList"
      | "addPartnerWhiteListBatch"
      | "adminWithdrawBEP20"
      | "adminWithdrawBNB"
      | "allUsers"
      | "blockAccPerShare"
      | "blockMining"
      | "blockRewardDebt"
      | "burnRate"
      | "buyNode"
      | "canDeposit"
      | "checkNodeQualified"
      | "claimDTeam"
      | "claimLP"
      | "claimNft"
      | "claimPartner"
      | "dAccPerShare"
      | "dRewardDebt"
      | "dThresholds"
      | "dTotalUsers"
      | "dailyReleaseRate"
      | "deposit"
      | "dqCard"
      | "dqPrice"
      | "dqToken"
      | "dynamicPool"
      | "feePool"
      | "foundationWallet"
      | "getBEP20Balance"
      | "getContractBalance"
      | "getCurrentMaxInvest"
      | "getLPStake"
      | "getPartnerCount"
      | "getPartnerWhiteList"
      | "getPrice"
      | "getSingleStake"
      | "getUser"
      | "insurancePool"
      | "isAddressRestricted"
      | "isPartnerWhite"
      | "isRestricted"
      | "lastBlockTime"
      | "levelRates"
      | "lpAccPerShare"
      | "lpPool"
      | "lpStakes"
      | "nftAccPerShare"
      | "nftRewardDebt"
      | "operationPool"
      | "owner"
      | "partnerAccPerShare"
      | "partnerDebt"
      | "partnerWhiteList"
      | "register"
      | "removePartnerWhiteList"
      | "renounceOwnership"
      | "restrictAddress"
      | "restrictAddressBatch"
      | "restrictedDebt"
      | "setFoundationWallet"
      | "setPrice"
      | "singleStakes"
      | "stakeFeeAccPerShare"
      | "stakePeriods"
      | "stakeRates"
      | "stakeSingle"
      | "startTime"
      | "totalLPShares"
      | "totalSingleStaked"
      | "transferOwnership"
      | "unrestrictAddress"
      | "unstakeSingle"
      | "withdrawDQ"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddPartnerWhiteList"
      | "BlockMining"
      | "BuyNode"
      | "ClaimDTeam"
      | "ClaimLP"
      | "ClaimNft"
      | "ClaimPartner"
      | "ClaimSingle"
      | "DLevelUp"
      | "Deposit"
      | "LevelUp"
      | "LineQualified"
      | "OwnershipTransferred"
      | "PriceUpdated"
      | "Register"
      | "RemovePartnerWhiteList"
      | "RestrictAddress"
      | "SetFoundationWallet"
      | "StakeSingle"
      | "UnrestrictAddress"
      | "UnstakeSingle"
      | "Withdraw"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "BEP20_TOKEN",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "BLACKHOLE", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "BURN_DECREMENT",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVEST_MAX_FINAL",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVEST_MAX_START",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVEST_MAX_STEP",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "INVEST_MIN",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_BURN_RATE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "PHASE_DURATION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addPartnerWhiteList",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addPartnerWhiteListBatch",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdrawBEP20",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "adminWithdrawBNB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "allUsers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "blockAccPerShare",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blockMining",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "blockRewardDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "burnRate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "buyNode",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "canDeposit",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkNodeQualified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimDTeam",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "claimLP", values?: undefined): string;
  encodeFunctionData(functionFragment: "claimNft", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "claimPartner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dAccPerShare",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dRewardDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "dThresholds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dTotalUsers",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyReleaseRate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "dqCard", values?: undefined): string;
  encodeFunctionData(functionFragment: "dqPrice", values?: undefined): string;
  encodeFunctionData(functionFragment: "dqToken", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "dynamicPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "feePool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "foundationWallet",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getBEP20Balance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getContractBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCurrentMaxInvest",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLPStake",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPartnerCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPartnerWhiteList",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSingleStake",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUser",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "insurancePool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAddressRestricted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPartnerWhite",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRestricted",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastBlockTime",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "levelRates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lpAccPerShare",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "lpPool", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lpStakes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "nftAccPerShare",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nftRewardDebt",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "operationPool",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "partnerAccPerShare",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "partnerDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "partnerWhiteList",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removePartnerWhiteList",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "restrictAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "restrictAddressBatch",
    values: [AddressLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "restrictedDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setFoundationWallet",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "singleStakes",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeFeeAccPerShare",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakePeriods",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeRates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "stakeSingle",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "startTime", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalLPShares",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSingleStaked",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unrestrictAddress",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unstakeSingle",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawDQ",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "BEP20_TOKEN",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "BLACKHOLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "BURN_DECREMENT",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVEST_MAX_FINAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVEST_MAX_START",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "INVEST_MAX_STEP",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "INVEST_MIN", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "MIN_BURN_RATE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "PHASE_DURATION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPartnerWhiteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addPartnerWhiteListBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdrawBEP20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "adminWithdrawBNB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "allUsers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "blockAccPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockMining",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "blockRewardDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burnRate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "buyNode", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canDeposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "checkNodeQualified",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimDTeam", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimLP", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimNft", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimPartner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dAccPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dRewardDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dThresholds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dTotalUsers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyReleaseRate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dqCard", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dqPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "dqToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "dynamicPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feePool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "foundationWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBEP20Balance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getContractBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCurrentMaxInvest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLPStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPartnerCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPartnerWhiteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getSingleStake",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getUser", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "insurancePool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAddressRestricted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPartnerWhite",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isRestricted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastBlockTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "levelRates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lpAccPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpPool", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "lpStakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nftAccPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nftRewardDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "operationPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "partnerAccPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "partnerDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "partnerWhiteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removePartnerWhiteList",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restrictAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restrictAddressBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "restrictedDebt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFoundationWallet",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "singleStakes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakeFeeAccPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakePeriods",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakeRates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "stakeSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "startTime", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalLPShares",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSingleStaked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unrestrictAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unstakeSingle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdrawDQ", data: BytesLike): Result;
}

export namespace AddPartnerWhiteListEvent {
  export type InputTuple = [partner: AddressLike];
  export type OutputTuple = [partner: string];
  export interface OutputObject {
    partner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BlockMiningEvent {
  export type InputTuple = [
    release: BigNumberish,
    burn: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [release: bigint, burn: bigint, timestamp: bigint];
  export interface OutputObject {
    release: bigint;
    burn: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace BuyNodeEvent {
  export type InputTuple = [
    user: AddressLike,
    cardType: BigNumberish,
    amount: BigNumberish
  ];
  export type OutputTuple = [user: string, cardType: bigint, amount: bigint];
  export interface OutputObject {
    user: string;
    cardType: bigint;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimDTeamEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimLPEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimNftEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimPartnerEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ClaimSingleEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DLevelUpEvent {
  export type InputTuple = [user: AddressLike, newDLevel: BigNumberish];
  export type OutputTuple = [user: string, newDLevel: bigint];
  export interface OutputObject {
    user: string;
    newDLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    dqAmount: BigNumberish,
    isFirst: boolean
  ];
  export type OutputTuple = [
    user: string,
    amount: bigint,
    dqAmount: bigint,
    isFirst: boolean
  ];
  export interface OutputObject {
    user: string;
    amount: bigint;
    dqAmount: bigint;
    isFirst: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LevelUpEvent {
  export type InputTuple = [user: AddressLike, newLevel: BigNumberish];
  export type OutputTuple = [user: string, newLevel: bigint];
  export interface OutputObject {
    user: string;
    newLevel: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LineQualifiedEvent {
  export type InputTuple = [user: AddressLike, lineCount: BigNumberish];
  export type OutputTuple = [user: string, lineCount: bigint];
  export interface OutputObject {
    user: string;
    lineCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceUpdatedEvent {
  export type InputTuple = [newPrice: BigNumberish];
  export type OutputTuple = [newPrice: bigint];
  export interface OutputObject {
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RegisterEvent {
  export type InputTuple = [user: AddressLike, referrer: AddressLike];
  export type OutputTuple = [user: string, referrer: string];
  export interface OutputObject {
    user: string;
    referrer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemovePartnerWhiteListEvent {
  export type InputTuple = [partner: AddressLike];
  export type OutputTuple = [partner: string];
  export interface OutputObject {
    partner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RestrictAddressEvent {
  export type InputTuple = [user: AddressLike, operator: AddressLike];
  export type OutputTuple = [user: string, operator: string];
  export interface OutputObject {
    user: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SetFoundationWalletEvent {
  export type InputTuple = [wallet: AddressLike];
  export type OutputTuple = [wallet: string];
  export interface OutputObject {
    wallet: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeSingleEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    period: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, period: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    period: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnrestrictAddressEvent {
  export type InputTuple = [user: AddressLike, operator: AddressLike];
  export type OutputTuple = [user: string, operator: string];
  export interface OutputObject {
    user: string;
    operator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnstakeSingleEvent {
  export type InputTuple = [
    user: AddressLike,
    amount: BigNumberish,
    period: BigNumberish
  ];
  export type OutputTuple = [user: string, amount: bigint, period: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
    period: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WithdrawEvent {
  export type InputTuple = [user: AddressLike, amount: BigNumberish];
  export type OutputTuple = [user: string, amount: bigint];
  export interface OutputObject {
    user: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DQProject extends BaseContract {
  connect(runner?: ContractRunner | null): DQProject;
  waitForDeployment(): Promise<this>;

  interface: DQProjectInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  BEP20_TOKEN: TypedContractMethod<[], [string], "view">;

  BLACKHOLE: TypedContractMethod<[], [string], "view">;

  BURN_DECREMENT: TypedContractMethod<[], [bigint], "view">;

  INVEST_MAX_FINAL: TypedContractMethod<[], [bigint], "view">;

  INVEST_MAX_START: TypedContractMethod<[], [bigint], "view">;

  INVEST_MAX_STEP: TypedContractMethod<[], [bigint], "view">;

  INVEST_MIN: TypedContractMethod<[], [bigint], "view">;

  MIN_BURN_RATE: TypedContractMethod<[], [bigint], "view">;

  PHASE_DURATION: TypedContractMethod<[], [bigint], "view">;

  addPartnerWhiteList: TypedContractMethod<
    [_partner: AddressLike],
    [void],
    "nonpayable"
  >;

  addPartnerWhiteListBatch: TypedContractMethod<
    [_partners: AddressLike[]],
    [void],
    "nonpayable"
  >;

  adminWithdrawBEP20: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  adminWithdrawBNB: TypedContractMethod<[], [void], "nonpayable">;

  allUsers: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  blockAccPerShare: TypedContractMethod<[], [bigint], "view">;

  blockMining: TypedContractMethod<[], [void], "nonpayable">;

  blockRewardDebt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  burnRate: TypedContractMethod<[], [bigint], "view">;

  buyNode: TypedContractMethod<[_type: BigNumberish], [void], "nonpayable">;

  canDeposit: TypedContractMethod<[_user: AddressLike], [boolean], "view">;

  checkNodeQualified: TypedContractMethod<
    [_user: AddressLike],
    [
      [boolean, bigint, bigint] & {
        qualified: boolean;
        currentLines: bigint;
        requiredLines: bigint;
      }
    ],
    "view"
  >;

  claimDTeam: TypedContractMethod<[], [void], "nonpayable">;

  claimLP: TypedContractMethod<[], [void], "nonpayable">;

  claimNft: TypedContractMethod<[], [void], "nonpayable">;

  claimPartner: TypedContractMethod<[], [void], "nonpayable">;

  dAccPerShare: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  dRewardDebt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  dThresholds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  dTotalUsers: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  dailyReleaseRate: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;

  dqCard: TypedContractMethod<[], [string], "view">;

  dqPrice: TypedContractMethod<[], [bigint], "view">;

  dqToken: TypedContractMethod<[], [string], "view">;

  dynamicPool: TypedContractMethod<[], [bigint], "view">;

  feePool: TypedContractMethod<[], [bigint], "view">;

  foundationWallet: TypedContractMethod<[], [string], "view">;

  getBEP20Balance: TypedContractMethod<[], [bigint], "view">;

  getContractBalance: TypedContractMethod<[], [bigint], "view">;

  getCurrentMaxInvest: TypedContractMethod<[], [bigint], "view">;

  getLPStake: TypedContractMethod<
    [_user: AddressLike],
    [[bigint, bigint] & { amount: bigint; startTime: bigint }],
    "view"
  >;

  getPartnerCount: TypedContractMethod<[], [bigint], "view">;

  getPartnerWhiteList: TypedContractMethod<[], [string[]], "view">;

  getPrice: TypedContractMethod<[], [bigint], "view">;

  getSingleStake: TypedContractMethod<
    [_user: AddressLike, _periodIndex: BigNumberish],
    [bigint],
    "view"
  >;

  getUser: TypedContractMethod<
    [_user: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        referrer: string;
        directCount: bigint;
        level: bigint;
        dLevel: bigint;
        totalInvest: bigint;
        teamInvest: bigint;
        energy: bigint;
        directSales: bigint;
        hasNode: boolean;
        hasDeposited: boolean;
        activeLineCount: bigint;
      }
    ],
    "view"
  >;

  insurancePool: TypedContractMethod<[], [bigint], "view">;

  isAddressRestricted: TypedContractMethod<
    [_user: AddressLike],
    [boolean],
    "view"
  >;

  isPartnerWhite: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isRestricted: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  lastBlockTime: TypedContractMethod<[], [bigint], "view">;

  levelRates: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  lpAccPerShare: TypedContractMethod<[], [bigint], "view">;

  lpPool: TypedContractMethod<[], [bigint], "view">;

  lpStakes: TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        amount: bigint;
        startTime: bigint;
        rewardDebt: bigint;
      }
    ],
    "view"
  >;

  nftAccPerShare: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  nftRewardDebt: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  operationPool: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  partnerAccPerShare: TypedContractMethod<[], [bigint], "view">;

  partnerDebt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  partnerWhiteList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  register: TypedContractMethod<[_referrer: AddressLike], [void], "nonpayable">;

  removePartnerWhiteList: TypedContractMethod<
    [_partner: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  restrictAddress: TypedContractMethod<
    [_user: AddressLike],
    [void],
    "nonpayable"
  >;

  restrictAddressBatch: TypedContractMethod<
    [_users: AddressLike[]],
    [void],
    "nonpayable"
  >;

  restrictedDebt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setFoundationWallet: TypedContractMethod<
    [_wallet: AddressLike],
    [void],
    "nonpayable"
  >;

  setPrice: TypedContractMethod<
    [_newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  singleStakes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  stakeFeeAccPerShare: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  stakePeriods: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  stakeRates: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  stakeSingle: TypedContractMethod<
    [_amount: BigNumberish, _periodIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  startTime: TypedContractMethod<[], [bigint], "view">;

  totalLPShares: TypedContractMethod<[], [bigint], "view">;

  totalSingleStaked: TypedContractMethod<
    [arg0: BigNumberish],
    [bigint],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unrestrictAddress: TypedContractMethod<
    [_user: AddressLike],
    [void],
    "nonpayable"
  >;

  unstakeSingle: TypedContractMethod<
    [_periodIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawDQ: TypedContractMethod<
    [_dqAmount: BigNumberish, _minOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "BEP20_TOKEN"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BLACKHOLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "BURN_DECREMENT"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INVEST_MAX_FINAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INVEST_MAX_START"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INVEST_MAX_STEP"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "INVEST_MIN"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_BURN_RATE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "PHASE_DURATION"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addPartnerWhiteList"
  ): TypedContractMethod<[_partner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addPartnerWhiteListBatch"
  ): TypedContractMethod<[_partners: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminWithdrawBEP20"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "adminWithdrawBNB"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "allUsers"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "blockAccPerShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "blockMining"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "blockRewardDebt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "burnRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "buyNode"
  ): TypedContractMethod<[_type: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canDeposit"
  ): TypedContractMethod<[_user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "checkNodeQualified"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [boolean, bigint, bigint] & {
        qualified: boolean;
        currentLines: bigint;
        requiredLines: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimDTeam"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimLP"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimNft"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimPartner"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dAccPerShare"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "dRewardDebt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "dThresholds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "dTotalUsers"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "dailyReleaseRate"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[_amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "dqCard"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dqPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dqToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dynamicPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feePool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "foundationWallet"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getBEP20Balance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getContractBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCurrentMaxInvest"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLPStake"
  ): TypedContractMethod<
    [_user: AddressLike],
    [[bigint, bigint] & { amount: bigint; startTime: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPartnerCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPartnerWhiteList"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getSingleStake"
  ): TypedContractMethod<
    [_user: AddressLike, _periodIndex: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUser"
  ): TypedContractMethod<
    [_user: AddressLike],
    [
      [
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        referrer: string;
        directCount: bigint;
        level: bigint;
        dLevel: bigint;
        totalInvest: bigint;
        teamInvest: bigint;
        energy: bigint;
        directSales: bigint;
        hasNode: boolean;
        hasDeposited: boolean;
        activeLineCount: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "insurancePool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAddressRestricted"
  ): TypedContractMethod<[_user: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPartnerWhite"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isRestricted"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastBlockTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "levelRates"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpAccPerShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpStakes"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [bigint, bigint, bigint] & {
        amount: bigint;
        startTime: bigint;
        rewardDebt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nftAccPerShare"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "nftRewardDebt"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "operationPool"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "partnerAccPerShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "partnerDebt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "partnerWhiteList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[_referrer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removePartnerWhiteList"
  ): TypedContractMethod<[_partner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "restrictAddress"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "restrictAddressBatch"
  ): TypedContractMethod<[_users: AddressLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "restrictedDebt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setFoundationWallet"
  ): TypedContractMethod<[_wallet: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPrice"
  ): TypedContractMethod<[_newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "singleStakes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "stakeFeeAccPerShare"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakePeriods"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakeRates"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "stakeSingle"
  ): TypedContractMethod<
    [_amount: BigNumberish, _periodIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "startTime"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalLPShares"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSingleStaked"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unrestrictAddress"
  ): TypedContractMethod<[_user: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unstakeSingle"
  ): TypedContractMethod<[_periodIndex: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawDQ"
  ): TypedContractMethod<
    [_dqAmount: BigNumberish, _minOut: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AddPartnerWhiteList"
  ): TypedContractEvent<
    AddPartnerWhiteListEvent.InputTuple,
    AddPartnerWhiteListEvent.OutputTuple,
    AddPartnerWhiteListEvent.OutputObject
  >;
  getEvent(
    key: "BlockMining"
  ): TypedContractEvent<
    BlockMiningEvent.InputTuple,
    BlockMiningEvent.OutputTuple,
    BlockMiningEvent.OutputObject
  >;
  getEvent(
    key: "BuyNode"
  ): TypedContractEvent<
    BuyNodeEvent.InputTuple,
    BuyNodeEvent.OutputTuple,
    BuyNodeEvent.OutputObject
  >;
  getEvent(
    key: "ClaimDTeam"
  ): TypedContractEvent<
    ClaimDTeamEvent.InputTuple,
    ClaimDTeamEvent.OutputTuple,
    ClaimDTeamEvent.OutputObject
  >;
  getEvent(
    key: "ClaimLP"
  ): TypedContractEvent<
    ClaimLPEvent.InputTuple,
    ClaimLPEvent.OutputTuple,
    ClaimLPEvent.OutputObject
  >;
  getEvent(
    key: "ClaimNft"
  ): TypedContractEvent<
    ClaimNftEvent.InputTuple,
    ClaimNftEvent.OutputTuple,
    ClaimNftEvent.OutputObject
  >;
  getEvent(
    key: "ClaimPartner"
  ): TypedContractEvent<
    ClaimPartnerEvent.InputTuple,
    ClaimPartnerEvent.OutputTuple,
    ClaimPartnerEvent.OutputObject
  >;
  getEvent(
    key: "ClaimSingle"
  ): TypedContractEvent<
    ClaimSingleEvent.InputTuple,
    ClaimSingleEvent.OutputTuple,
    ClaimSingleEvent.OutputObject
  >;
  getEvent(
    key: "DLevelUp"
  ): TypedContractEvent<
    DLevelUpEvent.InputTuple,
    DLevelUpEvent.OutputTuple,
    DLevelUpEvent.OutputObject
  >;
  getEvent(
    key: "Deposit"
  ): TypedContractEvent<
    DepositEvent.InputTuple,
    DepositEvent.OutputTuple,
    DepositEvent.OutputObject
  >;
  getEvent(
    key: "LevelUp"
  ): TypedContractEvent<
    LevelUpEvent.InputTuple,
    LevelUpEvent.OutputTuple,
    LevelUpEvent.OutputObject
  >;
  getEvent(
    key: "LineQualified"
  ): TypedContractEvent<
    LineQualifiedEvent.InputTuple,
    LineQualifiedEvent.OutputTuple,
    LineQualifiedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceUpdated"
  ): TypedContractEvent<
    PriceUpdatedEvent.InputTuple,
    PriceUpdatedEvent.OutputTuple,
    PriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Register"
  ): TypedContractEvent<
    RegisterEvent.InputTuple,
    RegisterEvent.OutputTuple,
    RegisterEvent.OutputObject
  >;
  getEvent(
    key: "RemovePartnerWhiteList"
  ): TypedContractEvent<
    RemovePartnerWhiteListEvent.InputTuple,
    RemovePartnerWhiteListEvent.OutputTuple,
    RemovePartnerWhiteListEvent.OutputObject
  >;
  getEvent(
    key: "RestrictAddress"
  ): TypedContractEvent<
    RestrictAddressEvent.InputTuple,
    RestrictAddressEvent.OutputTuple,
    RestrictAddressEvent.OutputObject
  >;
  getEvent(
    key: "SetFoundationWallet"
  ): TypedContractEvent<
    SetFoundationWalletEvent.InputTuple,
    SetFoundationWalletEvent.OutputTuple,
    SetFoundationWalletEvent.OutputObject
  >;
  getEvent(
    key: "StakeSingle"
  ): TypedContractEvent<
    StakeSingleEvent.InputTuple,
    StakeSingleEvent.OutputTuple,
    StakeSingleEvent.OutputObject
  >;
  getEvent(
    key: "UnrestrictAddress"
  ): TypedContractEvent<
    UnrestrictAddressEvent.InputTuple,
    UnrestrictAddressEvent.OutputTuple,
    UnrestrictAddressEvent.OutputObject
  >;
  getEvent(
    key: "UnstakeSingle"
  ): TypedContractEvent<
    UnstakeSingleEvent.InputTuple,
    UnstakeSingleEvent.OutputTuple,
    UnstakeSingleEvent.OutputObject
  >;
  getEvent(
    key: "Withdraw"
  ): TypedContractEvent<
    WithdrawEvent.InputTuple,
    WithdrawEvent.OutputTuple,
    WithdrawEvent.OutputObject
  >;

  filters: {
    "AddPartnerWhiteList(address)": TypedContractEvent<
      AddPartnerWhiteListEvent.InputTuple,
      AddPartnerWhiteListEvent.OutputTuple,
      AddPartnerWhiteListEvent.OutputObject
    >;
    AddPartnerWhiteList: TypedContractEvent<
      AddPartnerWhiteListEvent.InputTuple,
      AddPartnerWhiteListEvent.OutputTuple,
      AddPartnerWhiteListEvent.OutputObject
    >;

    "BlockMining(uint256,uint256,uint256)": TypedContractEvent<
      BlockMiningEvent.InputTuple,
      BlockMiningEvent.OutputTuple,
      BlockMiningEvent.OutputObject
    >;
    BlockMining: TypedContractEvent<
      BlockMiningEvent.InputTuple,
      BlockMiningEvent.OutputTuple,
      BlockMiningEvent.OutputObject
    >;

    "BuyNode(address,uint256,uint256)": TypedContractEvent<
      BuyNodeEvent.InputTuple,
      BuyNodeEvent.OutputTuple,
      BuyNodeEvent.OutputObject
    >;
    BuyNode: TypedContractEvent<
      BuyNodeEvent.InputTuple,
      BuyNodeEvent.OutputTuple,
      BuyNodeEvent.OutputObject
    >;

    "ClaimDTeam(address,uint256)": TypedContractEvent<
      ClaimDTeamEvent.InputTuple,
      ClaimDTeamEvent.OutputTuple,
      ClaimDTeamEvent.OutputObject
    >;
    ClaimDTeam: TypedContractEvent<
      ClaimDTeamEvent.InputTuple,
      ClaimDTeamEvent.OutputTuple,
      ClaimDTeamEvent.OutputObject
    >;

    "ClaimLP(address,uint256)": TypedContractEvent<
      ClaimLPEvent.InputTuple,
      ClaimLPEvent.OutputTuple,
      ClaimLPEvent.OutputObject
    >;
    ClaimLP: TypedContractEvent<
      ClaimLPEvent.InputTuple,
      ClaimLPEvent.OutputTuple,
      ClaimLPEvent.OutputObject
    >;

    "ClaimNft(address,uint256)": TypedContractEvent<
      ClaimNftEvent.InputTuple,
      ClaimNftEvent.OutputTuple,
      ClaimNftEvent.OutputObject
    >;
    ClaimNft: TypedContractEvent<
      ClaimNftEvent.InputTuple,
      ClaimNftEvent.OutputTuple,
      ClaimNftEvent.OutputObject
    >;

    "ClaimPartner(address,uint256)": TypedContractEvent<
      ClaimPartnerEvent.InputTuple,
      ClaimPartnerEvent.OutputTuple,
      ClaimPartnerEvent.OutputObject
    >;
    ClaimPartner: TypedContractEvent<
      ClaimPartnerEvent.InputTuple,
      ClaimPartnerEvent.OutputTuple,
      ClaimPartnerEvent.OutputObject
    >;

    "ClaimSingle(address,uint256)": TypedContractEvent<
      ClaimSingleEvent.InputTuple,
      ClaimSingleEvent.OutputTuple,
      ClaimSingleEvent.OutputObject
    >;
    ClaimSingle: TypedContractEvent<
      ClaimSingleEvent.InputTuple,
      ClaimSingleEvent.OutputTuple,
      ClaimSingleEvent.OutputObject
    >;

    "DLevelUp(address,uint8)": TypedContractEvent<
      DLevelUpEvent.InputTuple,
      DLevelUpEvent.OutputTuple,
      DLevelUpEvent.OutputObject
    >;
    DLevelUp: TypedContractEvent<
      DLevelUpEvent.InputTuple,
      DLevelUpEvent.OutputTuple,
      DLevelUpEvent.OutputObject
    >;

    "Deposit(address,uint256,uint256,bool)": TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;
    Deposit: TypedContractEvent<
      DepositEvent.InputTuple,
      DepositEvent.OutputTuple,
      DepositEvent.OutputObject
    >;

    "LevelUp(address,uint8)": TypedContractEvent<
      LevelUpEvent.InputTuple,
      LevelUpEvent.OutputTuple,
      LevelUpEvent.OutputObject
    >;
    LevelUp: TypedContractEvent<
      LevelUpEvent.InputTuple,
      LevelUpEvent.OutputTuple,
      LevelUpEvent.OutputObject
    >;

    "LineQualified(address,uint256)": TypedContractEvent<
      LineQualifiedEvent.InputTuple,
      LineQualifiedEvent.OutputTuple,
      LineQualifiedEvent.OutputObject
    >;
    LineQualified: TypedContractEvent<
      LineQualifiedEvent.InputTuple,
      LineQualifiedEvent.OutputTuple,
      LineQualifiedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceUpdated(uint256)": TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;
    PriceUpdated: TypedContractEvent<
      PriceUpdatedEvent.InputTuple,
      PriceUpdatedEvent.OutputTuple,
      PriceUpdatedEvent.OutputObject
    >;

    "Register(address,address)": TypedContractEvent<
      RegisterEvent.InputTuple,
      RegisterEvent.OutputTuple,
      RegisterEvent.OutputObject
    >;
    Register: TypedContractEvent<
      RegisterEvent.InputTuple,
      RegisterEvent.OutputTuple,
      RegisterEvent.OutputObject
    >;

    "RemovePartnerWhiteList(address)": TypedContractEvent<
      RemovePartnerWhiteListEvent.InputTuple,
      RemovePartnerWhiteListEvent.OutputTuple,
      RemovePartnerWhiteListEvent.OutputObject
    >;
    RemovePartnerWhiteList: TypedContractEvent<
      RemovePartnerWhiteListEvent.InputTuple,
      RemovePartnerWhiteListEvent.OutputTuple,
      RemovePartnerWhiteListEvent.OutputObject
    >;

    "RestrictAddress(address,address)": TypedContractEvent<
      RestrictAddressEvent.InputTuple,
      RestrictAddressEvent.OutputTuple,
      RestrictAddressEvent.OutputObject
    >;
    RestrictAddress: TypedContractEvent<
      RestrictAddressEvent.InputTuple,
      RestrictAddressEvent.OutputTuple,
      RestrictAddressEvent.OutputObject
    >;

    "SetFoundationWallet(address)": TypedContractEvent<
      SetFoundationWalletEvent.InputTuple,
      SetFoundationWalletEvent.OutputTuple,
      SetFoundationWalletEvent.OutputObject
    >;
    SetFoundationWallet: TypedContractEvent<
      SetFoundationWalletEvent.InputTuple,
      SetFoundationWalletEvent.OutputTuple,
      SetFoundationWalletEvent.OutputObject
    >;

    "StakeSingle(address,uint256,uint256)": TypedContractEvent<
      StakeSingleEvent.InputTuple,
      StakeSingleEvent.OutputTuple,
      StakeSingleEvent.OutputObject
    >;
    StakeSingle: TypedContractEvent<
      StakeSingleEvent.InputTuple,
      StakeSingleEvent.OutputTuple,
      StakeSingleEvent.OutputObject
    >;

    "UnrestrictAddress(address,address)": TypedContractEvent<
      UnrestrictAddressEvent.InputTuple,
      UnrestrictAddressEvent.OutputTuple,
      UnrestrictAddressEvent.OutputObject
    >;
    UnrestrictAddress: TypedContractEvent<
      UnrestrictAddressEvent.InputTuple,
      UnrestrictAddressEvent.OutputTuple,
      UnrestrictAddressEvent.OutputObject
    >;

    "UnstakeSingle(address,uint256,uint256)": TypedContractEvent<
      UnstakeSingleEvent.InputTuple,
      UnstakeSingleEvent.OutputTuple,
      UnstakeSingleEvent.OutputObject
    >;
    UnstakeSingle: TypedContractEvent<
      UnstakeSingleEvent.InputTuple,
      UnstakeSingleEvent.OutputTuple,
      UnstakeSingleEvent.OutputObject
    >;

    "Withdraw(address,uint256)": TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
    Withdraw: TypedContractEvent<
      WithdrawEvent.InputTuple,
      WithdrawEvent.OutputTuple,
      WithdrawEvent.OutputObject
    >;
  };
}
